/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.api;

import com.drpe.client.ApiCallback;
import com.drpe.client.ApiClient;
import com.drpe.client.ApiException;
import com.drpe.client.ApiResponse;
import com.drpe.client.Configuration;
import com.drpe.client.Pair;
import com.drpe.client.ProgressRequestBody;
import com.drpe.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.drpe.client.model.DsarRequest;
import com.drpe.client.model.DsarRequestStatus;
import com.drpe.client.model.DsarRequestType;
import com.drpe.client.model.DsarSubmitRequest;
import com.drpe.client.model.HTTPValidationError;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DsarApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DsarApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DsarApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getRequestApiV1DsarRequestsRequestIdGet
     * @param requestId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRequestApiV1DsarRequestsRequestIdGetCall(@javax.annotation.Nonnull String requestId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dsar/requests/{request_id}"
            .replace("{" + "request_id" + "}", localVarApiClient.escapeString(requestId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRequestApiV1DsarRequestsRequestIdGetValidateBeforeCall(@javax.annotation.Nonnull String requestId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'requestId' is set
        if (requestId == null) {
            throw new ApiException("Missing the required parameter 'requestId' when calling getRequestApiV1DsarRequestsRequestIdGet(Async)");
        }

        return getRequestApiV1DsarRequestsRequestIdGetCall(requestId, _callback);

    }

    /**
     * Get Request
     * 
     * @param requestId  (required)
     * @return DsarRequest
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public DsarRequest getRequestApiV1DsarRequestsRequestIdGet(@javax.annotation.Nonnull String requestId) throws ApiException {
        ApiResponse<DsarRequest> localVarResp = getRequestApiV1DsarRequestsRequestIdGetWithHttpInfo(requestId);
        return localVarResp.getData();
    }

    /**
     * Get Request
     * 
     * @param requestId  (required)
     * @return ApiResponse&lt;DsarRequest&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DsarRequest> getRequestApiV1DsarRequestsRequestIdGetWithHttpInfo(@javax.annotation.Nonnull String requestId) throws ApiException {
        okhttp3.Call localVarCall = getRequestApiV1DsarRequestsRequestIdGetValidateBeforeCall(requestId, null);
        Type localVarReturnType = new TypeToken<DsarRequest>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Request (asynchronously)
     * 
     * @param requestId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRequestApiV1DsarRequestsRequestIdGetAsync(@javax.annotation.Nonnull String requestId, final ApiCallback<DsarRequest> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRequestApiV1DsarRequestsRequestIdGetValidateBeforeCall(requestId, _callback);
        Type localVarReturnType = new TypeToken<DsarRequest>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listRequestsApiV1DsarRequestsGet
     * @param type  (optional)
     * @param status  (optional)
     * @param subjectId  (optional)
     * @param policyId  (optional)
     * @param limit  (optional, default to 100)
     * @param offset  (optional, default to 0)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listRequestsApiV1DsarRequestsGetCall(@javax.annotation.Nullable DsarRequestType type, @javax.annotation.Nullable DsarRequestStatus status, @javax.annotation.Nullable String subjectId, @javax.annotation.Nullable String policyId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dsar/requests";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (subjectId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("subject_id", subjectId));
        }

        if (policyId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("policy_id", policyId));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listRequestsApiV1DsarRequestsGetValidateBeforeCall(@javax.annotation.Nullable DsarRequestType type, @javax.annotation.Nullable DsarRequestStatus status, @javax.annotation.Nullable String subjectId, @javax.annotation.Nullable String policyId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback _callback) throws ApiException {
        return listRequestsApiV1DsarRequestsGetCall(type, status, subjectId, policyId, limit, offset, _callback);

    }

    /**
     * List Requests
     * 
     * @param type  (optional)
     * @param status  (optional)
     * @param subjectId  (optional)
     * @param policyId  (optional)
     * @param limit  (optional, default to 100)
     * @param offset  (optional, default to 0)
     * @return List&lt;DsarRequest&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public List<DsarRequest> listRequestsApiV1DsarRequestsGet(@javax.annotation.Nullable DsarRequestType type, @javax.annotation.Nullable DsarRequestStatus status, @javax.annotation.Nullable String subjectId, @javax.annotation.Nullable String policyId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
        ApiResponse<List<DsarRequest>> localVarResp = listRequestsApiV1DsarRequestsGetWithHttpInfo(type, status, subjectId, policyId, limit, offset);
        return localVarResp.getData();
    }

    /**
     * List Requests
     * 
     * @param type  (optional)
     * @param status  (optional)
     * @param subjectId  (optional)
     * @param policyId  (optional)
     * @param limit  (optional, default to 100)
     * @param offset  (optional, default to 0)
     * @return ApiResponse&lt;List&lt;DsarRequest&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<DsarRequest>> listRequestsApiV1DsarRequestsGetWithHttpInfo(@javax.annotation.Nullable DsarRequestType type, @javax.annotation.Nullable DsarRequestStatus status, @javax.annotation.Nullable String subjectId, @javax.annotation.Nullable String policyId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
        okhttp3.Call localVarCall = listRequestsApiV1DsarRequestsGetValidateBeforeCall(type, status, subjectId, policyId, limit, offset, null);
        Type localVarReturnType = new TypeToken<List<DsarRequest>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Requests (asynchronously)
     * 
     * @param type  (optional)
     * @param status  (optional)
     * @param subjectId  (optional)
     * @param policyId  (optional)
     * @param limit  (optional, default to 100)
     * @param offset  (optional, default to 0)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listRequestsApiV1DsarRequestsGetAsync(@javax.annotation.Nullable DsarRequestType type, @javax.annotation.Nullable DsarRequestStatus status, @javax.annotation.Nullable String subjectId, @javax.annotation.Nullable String policyId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback<List<DsarRequest>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listRequestsApiV1DsarRequestsGetValidateBeforeCall(type, status, subjectId, policyId, limit, offset, _callback);
        Type localVarReturnType = new TypeToken<List<DsarRequest>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for submitAccessApiV1DsarAccessPost
     * @param dsarSubmitRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitAccessApiV1DsarAccessPostCall(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = dsarSubmitRequest;

        // create path and map variables
        String localVarPath = "/api/v1/dsar/access";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call submitAccessApiV1DsarAccessPostValidateBeforeCall(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'dsarSubmitRequest' is set
        if (dsarSubmitRequest == null) {
            throw new ApiException("Missing the required parameter 'dsarSubmitRequest' when calling submitAccessApiV1DsarAccessPost(Async)");
        }

        return submitAccessApiV1DsarAccessPostCall(dsarSubmitRequest, _callback);

    }

    /**
     * Submit Access
     * 
     * @param dsarSubmitRequest  (required)
     * @return DsarRequest
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public DsarRequest submitAccessApiV1DsarAccessPost(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest) throws ApiException {
        ApiResponse<DsarRequest> localVarResp = submitAccessApiV1DsarAccessPostWithHttpInfo(dsarSubmitRequest);
        return localVarResp.getData();
    }

    /**
     * Submit Access
     * 
     * @param dsarSubmitRequest  (required)
     * @return ApiResponse&lt;DsarRequest&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DsarRequest> submitAccessApiV1DsarAccessPostWithHttpInfo(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest) throws ApiException {
        okhttp3.Call localVarCall = submitAccessApiV1DsarAccessPostValidateBeforeCall(dsarSubmitRequest, null);
        Type localVarReturnType = new TypeToken<DsarRequest>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Submit Access (asynchronously)
     * 
     * @param dsarSubmitRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitAccessApiV1DsarAccessPostAsync(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest, final ApiCallback<DsarRequest> _callback) throws ApiException {

        okhttp3.Call localVarCall = submitAccessApiV1DsarAccessPostValidateBeforeCall(dsarSubmitRequest, _callback);
        Type localVarReturnType = new TypeToken<DsarRequest>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for submitErasureApiV1DsarErasurePost
     * @param dsarSubmitRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitErasureApiV1DsarErasurePostCall(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = dsarSubmitRequest;

        // create path and map variables
        String localVarPath = "/api/v1/dsar/erasure";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call submitErasureApiV1DsarErasurePostValidateBeforeCall(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'dsarSubmitRequest' is set
        if (dsarSubmitRequest == null) {
            throw new ApiException("Missing the required parameter 'dsarSubmitRequest' when calling submitErasureApiV1DsarErasurePost(Async)");
        }

        return submitErasureApiV1DsarErasurePostCall(dsarSubmitRequest, _callback);

    }

    /**
     * Submit Erasure
     * 
     * @param dsarSubmitRequest  (required)
     * @return DsarRequest
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public DsarRequest submitErasureApiV1DsarErasurePost(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest) throws ApiException {
        ApiResponse<DsarRequest> localVarResp = submitErasureApiV1DsarErasurePostWithHttpInfo(dsarSubmitRequest);
        return localVarResp.getData();
    }

    /**
     * Submit Erasure
     * 
     * @param dsarSubmitRequest  (required)
     * @return ApiResponse&lt;DsarRequest&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DsarRequest> submitErasureApiV1DsarErasurePostWithHttpInfo(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest) throws ApiException {
        okhttp3.Call localVarCall = submitErasureApiV1DsarErasurePostValidateBeforeCall(dsarSubmitRequest, null);
        Type localVarReturnType = new TypeToken<DsarRequest>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Submit Erasure (asynchronously)
     * 
     * @param dsarSubmitRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitErasureApiV1DsarErasurePostAsync(@javax.annotation.Nonnull DsarSubmitRequest dsarSubmitRequest, final ApiCallback<DsarRequest> _callback) throws ApiException {

        okhttp3.Call localVarCall = submitErasureApiV1DsarErasurePostValidateBeforeCall(dsarSubmitRequest, _callback);
        Type localVarReturnType = new TypeToken<DsarRequest>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
