/*
ROS Policy

Testing SystemsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package drpe

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/drpe/drpe/drpe"
)

func Test_drpe_SystemsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SystemsAPIService CreateSystemApiV1SystemsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SystemsAPI.CreateSystemApiV1SystemsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemsAPIService DeleteSystemApiV1SystemsSystemIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var systemId string

		httpRes, err := apiClient.SystemsAPI.DeleteSystemApiV1SystemsSystemIdDelete(context.Background(), systemId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemsAPIService GetSystemApiV1SystemsSystemIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var systemId string

		resp, httpRes, err := apiClient.SystemsAPI.GetSystemApiV1SystemsSystemIdGet(context.Background(), systemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemsAPIService ListSystemPoliciesApiV1SystemsSystemIdPoliciesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var systemId string

		resp, httpRes, err := apiClient.SystemsAPI.ListSystemPoliciesApiV1SystemsSystemIdPoliciesGet(context.Background(), systemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemsAPIService ListSystemsApiV1SystemsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SystemsAPI.ListSystemsApiV1SystemsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemsAPIService SetSystemPoliciesApiV1SystemsSystemIdPoliciesPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var systemId string

		resp, httpRes, err := apiClient.SystemsAPI.SetSystemPoliciesApiV1SystemsSystemIdPoliciesPut(context.Background(), systemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemsAPIService UpdateSystemApiV1SystemsSystemIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var systemId string

		resp, httpRes, err := apiClient.SystemsAPI.UpdateSystemApiV1SystemsSystemIdPatch(context.Background(), systemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
