/*
ROS Policy

Testing PrivacyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package drpe

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/drpe/drpe/drpe"
)

func Test_drpe_PrivacyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PrivacyAPIService PrivacyMaskApiV1PrivacyMaskPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PrivacyAPI.PrivacyMaskApiV1PrivacyMaskPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrivacyAPIService PrivacyStatusApiV1PrivacyStatusGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PrivacyAPI.PrivacyStatusApiV1PrivacyStatusGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrivacyAPIService PrivacyUnmaskApiV1PrivacyUnmaskPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PrivacyAPI.PrivacyUnmaskApiV1PrivacyUnmaskPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
