/*
DRPE — Data Retention Policy Engine

Testing PoliciesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package drpe

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/drpe/drpe/drpe"
)

func Test_drpe_PoliciesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PoliciesAPIService ActivatePolicyVersionApiV1PoliciesPolicyIdVersionsVerActivatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyId string
		var ver int32

		resp, httpRes, err := apiClient.PoliciesAPI.ActivatePolicyVersionApiV1PoliciesPolicyIdVersionsVerActivatePost(context.Background(), policyId, ver).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService CreatePolicyApiV1PoliciesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PoliciesAPI.CreatePolicyApiV1PoliciesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService DeletePolicyApiV1PoliciesPolicyIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyId string

		resp, httpRes, err := apiClient.PoliciesAPI.DeletePolicyApiV1PoliciesPolicyIdDelete(context.Background(), policyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService DiffPolicyVersionsApiV1PoliciesPolicyIdDiffPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyId string

		resp, httpRes, err := apiClient.PoliciesAPI.DiffPolicyVersionsApiV1PoliciesPolicyIdDiffPost(context.Background(), policyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService GetPolicyApiV1PoliciesPolicyIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyId string

		resp, httpRes, err := apiClient.PoliciesAPI.GetPolicyApiV1PoliciesPolicyIdGet(context.Background(), policyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService GetPolicyVersionApiV1PoliciesPolicyIdVersionsVerGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyId string
		var ver int32

		resp, httpRes, err := apiClient.PoliciesAPI.GetPolicyVersionApiV1PoliciesPolicyIdVersionsVerGet(context.Background(), policyId, ver).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService ImportPoliciesApiV1PoliciesImportPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PoliciesAPI.ImportPoliciesApiV1PoliciesImportPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService ListPoliciesApiV1PoliciesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PoliciesAPI.ListPoliciesApiV1PoliciesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService ListPolicyVersionsApiV1PoliciesPolicyIdVersionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyId string

		resp, httpRes, err := apiClient.PoliciesAPI.ListPolicyVersionsApiV1PoliciesPolicyIdVersionsGet(context.Background(), policyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService UpdatePolicyApiV1PoliciesPolicyIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyId string

		resp, httpRes, err := apiClient.PoliciesAPI.UpdatePolicyApiV1PoliciesPolicyIdPut(context.Background(), policyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoliciesAPIService ValidatePolicyApiV1PoliciesValidatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PoliciesAPI.ValidatePolicyApiV1PoliciesValidatePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
