/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportRequest{}

// ImportRequest struct for ImportRequest
type ImportRequest struct {
	Yaml string `json:"yaml"`
	ReferenceSources []ReferenceSource `json:"reference_sources,omitempty"`
}

type _ImportRequest ImportRequest

// NewImportRequest instantiates a new ImportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportRequest(yaml string) *ImportRequest {
	this := ImportRequest{}
	this.Yaml = yaml
	return &this
}

// NewImportRequestWithDefaults instantiates a new ImportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportRequestWithDefaults() *ImportRequest {
	this := ImportRequest{}
	return &this
}

// GetYaml returns the Yaml field value
func (o *ImportRequest) GetYaml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Yaml
}

// GetYamlOk returns a tuple with the Yaml field value
// and a boolean to check if the value has been set.
func (o *ImportRequest) GetYamlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Yaml, true
}

// SetYaml sets field value
func (o *ImportRequest) SetYaml(v string) {
	o.Yaml = v
}

// GetReferenceSources returns the ReferenceSources field value if set, zero value otherwise.
func (o *ImportRequest) GetReferenceSources() []ReferenceSource {
	if o == nil || IsNil(o.ReferenceSources) {
		var ret []ReferenceSource
		return ret
	}
	return o.ReferenceSources
}

// GetReferenceSourcesOk returns a tuple with the ReferenceSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportRequest) GetReferenceSourcesOk() ([]ReferenceSource, bool) {
	if o == nil || IsNil(o.ReferenceSources) {
		return nil, false
	}
	return o.ReferenceSources, true
}

// HasReferenceSources returns a boolean if a field has been set.
func (o *ImportRequest) HasReferenceSources() bool {
	if o != nil && !IsNil(o.ReferenceSources) {
		return true
	}

	return false
}

// SetReferenceSources gets a reference to the given []ReferenceSource and assigns it to the ReferenceSources field.
func (o *ImportRequest) SetReferenceSources(v []ReferenceSource) {
	o.ReferenceSources = v
}

func (o ImportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["yaml"] = o.Yaml
	if !IsNil(o.ReferenceSources) {
		toSerialize["reference_sources"] = o.ReferenceSources
	}
	return toSerialize, nil
}

func (o *ImportRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"yaml",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportRequest := _ImportRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportRequest)

	if err != nil {
		return err
	}

	*o = ImportRequest(varImportRequest)

	return err
}

type NullableImportRequest struct {
	value *ImportRequest
	isSet bool
}

func (v NullableImportRequest) Get() *ImportRequest {
	return v.value
}

func (v *NullableImportRequest) Set(val *ImportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportRequest(val *ImportRequest) *NullableImportRequest {
	return &NullableImportRequest{value: val, isSet: true}
}

func (v NullableImportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


