/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemCreateRequest{}

// SystemCreateRequest POST /api/v1/systems body.
type SystemCreateRequest struct {
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	Owner NullableString `json:"owner,omitempty"`
	Status *CatalogStatus `json:"status,omitempty"`
	SourceKey NullableString `json:"source_key,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

type _SystemCreateRequest SystemCreateRequest

// NewSystemCreateRequest instantiates a new SystemCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemCreateRequest(name string) *SystemCreateRequest {
	this := SystemCreateRequest{}
	this.Name = name
	return &this
}

// NewSystemCreateRequestWithDefaults instantiates a new SystemCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemCreateRequestWithDefaults() *SystemCreateRequest {
	this := SystemCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SystemCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SystemCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SystemCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SystemCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SystemCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SystemCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SystemCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemCreateRequest) GetOwner() string {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret string
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemCreateRequest) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *SystemCreateRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableString and assigns it to the Owner field.
func (o *SystemCreateRequest) SetOwner(v string) {
	o.Owner.Set(&v)
}
// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *SystemCreateRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *SystemCreateRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SystemCreateRequest) GetStatus() CatalogStatus {
	if o == nil || IsNil(o.Status) {
		var ret CatalogStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemCreateRequest) GetStatusOk() (*CatalogStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SystemCreateRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CatalogStatus and assigns it to the Status field.
func (o *SystemCreateRequest) SetStatus(v CatalogStatus) {
	o.Status = &v
}

// GetSourceKey returns the SourceKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemCreateRequest) GetSourceKey() string {
	if o == nil || IsNil(o.SourceKey.Get()) {
		var ret string
		return ret
	}
	return *o.SourceKey.Get()
}

// GetSourceKeyOk returns a tuple with the SourceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemCreateRequest) GetSourceKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceKey.Get(), o.SourceKey.IsSet()
}

// HasSourceKey returns a boolean if a field has been set.
func (o *SystemCreateRequest) HasSourceKey() bool {
	if o != nil && o.SourceKey.IsSet() {
		return true
	}

	return false
}

// SetSourceKey gets a reference to the given NullableString and assigns it to the SourceKey field.
func (o *SystemCreateRequest) SetSourceKey(v string) {
	o.SourceKey.Set(&v)
}
// SetSourceKeyNil sets the value for SourceKey to be an explicit nil
func (o *SystemCreateRequest) SetSourceKeyNil() {
	o.SourceKey.Set(nil)
}

// UnsetSourceKey ensures that no value is present for SourceKey, not even an explicit nil
func (o *SystemCreateRequest) UnsetSourceKey() {
	o.SourceKey.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SystemCreateRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemCreateRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SystemCreateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SystemCreateRequest) SetTags(v []string) {
	o.Tags = v
}

func (o SystemCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.SourceKey.IsSet() {
		toSerialize["source_key"] = o.SourceKey.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *SystemCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemCreateRequest := _SystemCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemCreateRequest)

	if err != nil {
		return err
	}

	*o = SystemCreateRequest(varSystemCreateRequest)

	return err
}

type NullableSystemCreateRequest struct {
	value *SystemCreateRequest
	isSet bool
}

func (v NullableSystemCreateRequest) Get() *SystemCreateRequest {
	return v.value
}

func (v *NullableSystemCreateRequest) Set(val *SystemCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemCreateRequest(val *SystemCreateRequest) *NullableSystemCreateRequest {
	return &NullableSystemCreateRequest{value: val, isSet: true}
}

func (v NullableSystemCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


