/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GuardEventModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuardEventModel{}

// GuardEventModel struct for GuardEventModel
type GuardEventModel struct {
	Kind string `json:"kind"`
	ObservationPoint string `json:"observation_point"`
	Subject map[string]interface{} `json:"subject,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	EventId string `json:"event_id"`
	GuardId string `json:"guard_id"`
	Timestamp string `json:"timestamp"`
	SessionId NullableString `json:"session_id,omitempty"`
	LlmProtocol NullableString `json:"llm_protocol,omitempty"`
	ContextRefs []string `json:"context_refs,omitempty"`
	Provenance []ProvenanceModel `json:"provenance,omitempty"`
	OgrVersion *string `json:"ogr_version,omitempty"`
}

type _GuardEventModel GuardEventModel

// NewGuardEventModel instantiates a new GuardEventModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuardEventModel(kind string, observationPoint string, eventId string, guardId string, timestamp string) *GuardEventModel {
	this := GuardEventModel{}
	this.Kind = kind
	this.ObservationPoint = observationPoint
	this.EventId = eventId
	this.GuardId = guardId
	this.Timestamp = timestamp
	var ogrVersion string = "0.1"
	this.OgrVersion = &ogrVersion
	return &this
}

// NewGuardEventModelWithDefaults instantiates a new GuardEventModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuardEventModelWithDefaults() *GuardEventModel {
	this := GuardEventModel{}
	var ogrVersion string = "0.1"
	this.OgrVersion = &ogrVersion
	return &this
}

// GetKind returns the Kind field value
func (o *GuardEventModel) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *GuardEventModel) SetKind(v string) {
	o.Kind = v
}

// GetObservationPoint returns the ObservationPoint field value
func (o *GuardEventModel) GetObservationPoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObservationPoint
}

// GetObservationPointOk returns a tuple with the ObservationPoint field value
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetObservationPointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservationPoint, true
}

// SetObservationPoint sets field value
func (o *GuardEventModel) SetObservationPoint(v string) {
	o.ObservationPoint = v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *GuardEventModel) GetSubject() map[string]interface{} {
	if o == nil || IsNil(o.Subject) {
		var ret map[string]interface{}
		return ret
	}
	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetSubjectOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Subject) {
		return map[string]interface{}{}, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *GuardEventModel) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given map[string]interface{} and assigns it to the Subject field.
func (o *GuardEventModel) SetSubject(v map[string]interface{}) {
	o.Subject = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *GuardEventModel) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *GuardEventModel) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *GuardEventModel) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetEventId returns the EventId field value
func (o *GuardEventModel) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *GuardEventModel) SetEventId(v string) {
	o.EventId = v
}

// GetGuardId returns the GuardId field value
func (o *GuardEventModel) GetGuardId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GuardId
}

// GetGuardIdOk returns a tuple with the GuardId field value
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetGuardIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GuardId, true
}

// SetGuardId sets field value
func (o *GuardEventModel) SetGuardId(v string) {
	o.GuardId = v
}

// GetTimestamp returns the Timestamp field value
func (o *GuardEventModel) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *GuardEventModel) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GuardEventModel) GetSessionId() string {
	if o == nil || IsNil(o.SessionId.Get()) {
		var ret string
		return ret
	}
	return *o.SessionId.Get()
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GuardEventModel) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SessionId.Get(), o.SessionId.IsSet()
}

// HasSessionId returns a boolean if a field has been set.
func (o *GuardEventModel) HasSessionId() bool {
	if o != nil && o.SessionId.IsSet() {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given NullableString and assigns it to the SessionId field.
func (o *GuardEventModel) SetSessionId(v string) {
	o.SessionId.Set(&v)
}
// SetSessionIdNil sets the value for SessionId to be an explicit nil
func (o *GuardEventModel) SetSessionIdNil() {
	o.SessionId.Set(nil)
}

// UnsetSessionId ensures that no value is present for SessionId, not even an explicit nil
func (o *GuardEventModel) UnsetSessionId() {
	o.SessionId.Unset()
}

// GetLlmProtocol returns the LlmProtocol field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GuardEventModel) GetLlmProtocol() string {
	if o == nil || IsNil(o.LlmProtocol.Get()) {
		var ret string
		return ret
	}
	return *o.LlmProtocol.Get()
}

// GetLlmProtocolOk returns a tuple with the LlmProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GuardEventModel) GetLlmProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmProtocol.Get(), o.LlmProtocol.IsSet()
}

// HasLlmProtocol returns a boolean if a field has been set.
func (o *GuardEventModel) HasLlmProtocol() bool {
	if o != nil && o.LlmProtocol.IsSet() {
		return true
	}

	return false
}

// SetLlmProtocol gets a reference to the given NullableString and assigns it to the LlmProtocol field.
func (o *GuardEventModel) SetLlmProtocol(v string) {
	o.LlmProtocol.Set(&v)
}
// SetLlmProtocolNil sets the value for LlmProtocol to be an explicit nil
func (o *GuardEventModel) SetLlmProtocolNil() {
	o.LlmProtocol.Set(nil)
}

// UnsetLlmProtocol ensures that no value is present for LlmProtocol, not even an explicit nil
func (o *GuardEventModel) UnsetLlmProtocol() {
	o.LlmProtocol.Unset()
}

// GetContextRefs returns the ContextRefs field value if set, zero value otherwise.
func (o *GuardEventModel) GetContextRefs() []string {
	if o == nil || IsNil(o.ContextRefs) {
		var ret []string
		return ret
	}
	return o.ContextRefs
}

// GetContextRefsOk returns a tuple with the ContextRefs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetContextRefsOk() ([]string, bool) {
	if o == nil || IsNil(o.ContextRefs) {
		return nil, false
	}
	return o.ContextRefs, true
}

// HasContextRefs returns a boolean if a field has been set.
func (o *GuardEventModel) HasContextRefs() bool {
	if o != nil && !IsNil(o.ContextRefs) {
		return true
	}

	return false
}

// SetContextRefs gets a reference to the given []string and assigns it to the ContextRefs field.
func (o *GuardEventModel) SetContextRefs(v []string) {
	o.ContextRefs = v
}

// GetProvenance returns the Provenance field value if set, zero value otherwise.
func (o *GuardEventModel) GetProvenance() []ProvenanceModel {
	if o == nil || IsNil(o.Provenance) {
		var ret []ProvenanceModel
		return ret
	}
	return o.Provenance
}

// GetProvenanceOk returns a tuple with the Provenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetProvenanceOk() ([]ProvenanceModel, bool) {
	if o == nil || IsNil(o.Provenance) {
		return nil, false
	}
	return o.Provenance, true
}

// HasProvenance returns a boolean if a field has been set.
func (o *GuardEventModel) HasProvenance() bool {
	if o != nil && !IsNil(o.Provenance) {
		return true
	}

	return false
}

// SetProvenance gets a reference to the given []ProvenanceModel and assigns it to the Provenance field.
func (o *GuardEventModel) SetProvenance(v []ProvenanceModel) {
	o.Provenance = v
}

// GetOgrVersion returns the OgrVersion field value if set, zero value otherwise.
func (o *GuardEventModel) GetOgrVersion() string {
	if o == nil || IsNil(o.OgrVersion) {
		var ret string
		return ret
	}
	return *o.OgrVersion
}

// GetOgrVersionOk returns a tuple with the OgrVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardEventModel) GetOgrVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OgrVersion) {
		return nil, false
	}
	return o.OgrVersion, true
}

// HasOgrVersion returns a boolean if a field has been set.
func (o *GuardEventModel) HasOgrVersion() bool {
	if o != nil && !IsNil(o.OgrVersion) {
		return true
	}

	return false
}

// SetOgrVersion gets a reference to the given string and assigns it to the OgrVersion field.
func (o *GuardEventModel) SetOgrVersion(v string) {
	o.OgrVersion = &v
}

func (o GuardEventModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuardEventModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["observation_point"] = o.ObservationPoint
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	toSerialize["event_id"] = o.EventId
	toSerialize["guard_id"] = o.GuardId
	toSerialize["timestamp"] = o.Timestamp
	if o.SessionId.IsSet() {
		toSerialize["session_id"] = o.SessionId.Get()
	}
	if o.LlmProtocol.IsSet() {
		toSerialize["llm_protocol"] = o.LlmProtocol.Get()
	}
	if !IsNil(o.ContextRefs) {
		toSerialize["context_refs"] = o.ContextRefs
	}
	if !IsNil(o.Provenance) {
		toSerialize["provenance"] = o.Provenance
	}
	if !IsNil(o.OgrVersion) {
		toSerialize["ogr_version"] = o.OgrVersion
	}
	return toSerialize, nil
}

func (o *GuardEventModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"observation_point",
		"event_id",
		"guard_id",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGuardEventModel := _GuardEventModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGuardEventModel)

	if err != nil {
		return err
	}

	*o = GuardEventModel(varGuardEventModel)

	return err
}

type NullableGuardEventModel struct {
	value *GuardEventModel
	isSet bool
}

func (v NullableGuardEventModel) Get() *GuardEventModel {
	return v.value
}

func (v *NullableGuardEventModel) Set(val *GuardEventModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGuardEventModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGuardEventModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuardEventModel(val *GuardEventModel) *NullableGuardEventModel {
	return &NullableGuardEventModel{value: val, isSet: true}
}

func (v NullableGuardEventModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuardEventModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


