/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CategoryModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryModel{}

// CategoryModel struct for CategoryModel
type CategoryModel struct {
	Id string `json:"id"`
	Domain string `json:"domain"`
	Score *float32 `json:"score,omitempty"`
}

type _CategoryModel CategoryModel

// NewCategoryModel instantiates a new CategoryModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryModel(id string, domain string) *CategoryModel {
	this := CategoryModel{}
	this.Id = id
	this.Domain = domain
	var score float32 = 1.0
	this.Score = &score
	return &this
}

// NewCategoryModelWithDefaults instantiates a new CategoryModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryModelWithDefaults() *CategoryModel {
	this := CategoryModel{}
	var score float32 = 1.0
	this.Score = &score
	return &this
}

// GetId returns the Id field value
func (o *CategoryModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CategoryModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CategoryModel) SetId(v string) {
	o.Id = v
}

// GetDomain returns the Domain field value
func (o *CategoryModel) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CategoryModel) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CategoryModel) SetDomain(v string) {
	o.Domain = v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *CategoryModel) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryModel) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *CategoryModel) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *CategoryModel) SetScore(v float32) {
	o.Score = &v
}

func (o CategoryModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["domain"] = o.Domain
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	return toSerialize, nil
}

func (o *CategoryModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryModel := _CategoryModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCategoryModel)

	if err != nil {
		return err
	}

	*o = CategoryModel(varCategoryModel)

	return err
}

type NullableCategoryModel struct {
	value *CategoryModel
	isSet bool
}

func (v NullableCategoryModel) Get() *CategoryModel {
	return v.value
}

func (v *NullableCategoryModel) Set(val *CategoryModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryModel(val *CategoryModel) *NullableCategoryModel {
	return &NullableCategoryModel{value: val, isSet: true}
}

func (v NullableCategoryModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


