/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GuardrailPolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuardrailPolicyResponse{}

// GuardrailPolicyResponse struct for GuardrailPolicyResponse
type GuardrailPolicyResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Policy map[string]interface{} `json:"policy"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _GuardrailPolicyResponse GuardrailPolicyResponse

// NewGuardrailPolicyResponse instantiates a new GuardrailPolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuardrailPolicyResponse(id string, name string, policy map[string]interface{}, createdAt time.Time, updatedAt time.Time) *GuardrailPolicyResponse {
	this := GuardrailPolicyResponse{}
	this.Id = id
	this.Name = name
	this.Policy = policy
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGuardrailPolicyResponseWithDefaults instantiates a new GuardrailPolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuardrailPolicyResponseWithDefaults() *GuardrailPolicyResponse {
	this := GuardrailPolicyResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GuardrailPolicyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GuardrailPolicyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GuardrailPolicyResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GuardrailPolicyResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GuardrailPolicyResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GuardrailPolicyResponse) SetName(v string) {
	o.Name = v
}

// GetPolicy returns the Policy field value
func (o *GuardrailPolicyResponse) GetPolicy() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *GuardrailPolicyResponse) GetPolicyOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Policy, true
}

// SetPolicy sets field value
func (o *GuardrailPolicyResponse) SetPolicy(v map[string]interface{}) {
	o.Policy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GuardrailPolicyResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GuardrailPolicyResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GuardrailPolicyResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GuardrailPolicyResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GuardrailPolicyResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GuardrailPolicyResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o GuardrailPolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuardrailPolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["policy"] = o.Policy
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *GuardrailPolicyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"policy",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGuardrailPolicyResponse := _GuardrailPolicyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGuardrailPolicyResponse)

	if err != nil {
		return err
	}

	*o = GuardrailPolicyResponse(varGuardrailPolicyResponse)

	return err
}

type NullableGuardrailPolicyResponse struct {
	value *GuardrailPolicyResponse
	isSet bool
}

func (v NullableGuardrailPolicyResponse) Get() *GuardrailPolicyResponse {
	return v.value
}

func (v *NullableGuardrailPolicyResponse) Set(val *GuardrailPolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGuardrailPolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGuardrailPolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuardrailPolicyResponse(val *GuardrailPolicyResponse) *NullableGuardrailPolicyResponse {
	return &NullableGuardrailPolicyResponse{value: val, isSet: true}
}

func (v NullableGuardrailPolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuardrailPolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


