/*
DRPE — Data Retention Policy Engine

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AuditEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditEntry{}

// AuditEntry Immutable audit log entry.
type AuditEntry struct {
	Id string `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	EventType AuditEventType `json:"event_type"`
	PolicyId NullableString `json:"policy_id,omitempty"`
	RuleId NullableString `json:"rule_id,omitempty"`
	RecordId NullableString `json:"record_id,omitempty"`
	Action NullableString `json:"action,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	JobId NullableString `json:"job_id,omitempty"`
	EvaluationId NullableString `json:"evaluation_id,omitempty"`
}

type _AuditEntry AuditEntry

// NewAuditEntry instantiates a new AuditEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditEntry(id string, createdAt time.Time, eventType AuditEventType) *AuditEntry {
	this := AuditEntry{}
	this.Id = id
	this.CreatedAt = createdAt
	this.EventType = eventType
	return &this
}

// NewAuditEntryWithDefaults instantiates a new AuditEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditEntryWithDefaults() *AuditEntry {
	this := AuditEntry{}
	return &this
}

// GetId returns the Id field value
func (o *AuditEntry) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AuditEntry) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AuditEntry) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AuditEntry) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AuditEntry) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AuditEntry) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEventType returns the EventType field value
func (o *AuditEntry) GetEventType() AuditEventType {
	if o == nil {
		var ret AuditEventType
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *AuditEntry) GetEventTypeOk() (*AuditEventType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *AuditEntry) SetEventType(v AuditEventType) {
	o.EventType = v
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuditEntry) GetPolicyId() string {
	if o == nil || IsNil(o.PolicyId.Get()) {
		var ret string
		return ret
	}
	return *o.PolicyId.Get()
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditEntry) GetPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyId.Get(), o.PolicyId.IsSet()
}

// HasPolicyId returns a boolean if a field has been set.
func (o *AuditEntry) HasPolicyId() bool {
	if o != nil && o.PolicyId.IsSet() {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given NullableString and assigns it to the PolicyId field.
func (o *AuditEntry) SetPolicyId(v string) {
	o.PolicyId.Set(&v)
}
// SetPolicyIdNil sets the value for PolicyId to be an explicit nil
func (o *AuditEntry) SetPolicyIdNil() {
	o.PolicyId.Set(nil)
}

// UnsetPolicyId ensures that no value is present for PolicyId, not even an explicit nil
func (o *AuditEntry) UnsetPolicyId() {
	o.PolicyId.Unset()
}

// GetRuleId returns the RuleId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuditEntry) GetRuleId() string {
	if o == nil || IsNil(o.RuleId.Get()) {
		var ret string
		return ret
	}
	return *o.RuleId.Get()
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditEntry) GetRuleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuleId.Get(), o.RuleId.IsSet()
}

// HasRuleId returns a boolean if a field has been set.
func (o *AuditEntry) HasRuleId() bool {
	if o != nil && o.RuleId.IsSet() {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given NullableString and assigns it to the RuleId field.
func (o *AuditEntry) SetRuleId(v string) {
	o.RuleId.Set(&v)
}
// SetRuleIdNil sets the value for RuleId to be an explicit nil
func (o *AuditEntry) SetRuleIdNil() {
	o.RuleId.Set(nil)
}

// UnsetRuleId ensures that no value is present for RuleId, not even an explicit nil
func (o *AuditEntry) UnsetRuleId() {
	o.RuleId.Unset()
}

// GetRecordId returns the RecordId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuditEntry) GetRecordId() string {
	if o == nil || IsNil(o.RecordId.Get()) {
		var ret string
		return ret
	}
	return *o.RecordId.Get()
}

// GetRecordIdOk returns a tuple with the RecordId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditEntry) GetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecordId.Get(), o.RecordId.IsSet()
}

// HasRecordId returns a boolean if a field has been set.
func (o *AuditEntry) HasRecordId() bool {
	if o != nil && o.RecordId.IsSet() {
		return true
	}

	return false
}

// SetRecordId gets a reference to the given NullableString and assigns it to the RecordId field.
func (o *AuditEntry) SetRecordId(v string) {
	o.RecordId.Set(&v)
}
// SetRecordIdNil sets the value for RecordId to be an explicit nil
func (o *AuditEntry) SetRecordIdNil() {
	o.RecordId.Set(nil)
}

// UnsetRecordId ensures that no value is present for RecordId, not even an explicit nil
func (o *AuditEntry) UnsetRecordId() {
	o.RecordId.Unset()
}

// GetAction returns the Action field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuditEntry) GetAction() string {
	if o == nil || IsNil(o.Action.Get()) {
		var ret string
		return ret
	}
	return *o.Action.Get()
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditEntry) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Action.Get(), o.Action.IsSet()
}

// HasAction returns a boolean if a field has been set.
func (o *AuditEntry) HasAction() bool {
	if o != nil && o.Action.IsSet() {
		return true
	}

	return false
}

// SetAction gets a reference to the given NullableString and assigns it to the Action field.
func (o *AuditEntry) SetAction(v string) {
	o.Action.Set(&v)
}
// SetActionNil sets the value for Action to be an explicit nil
func (o *AuditEntry) SetActionNil() {
	o.Action.Set(nil)
}

// UnsetAction ensures that no value is present for Action, not even an explicit nil
func (o *AuditEntry) UnsetAction() {
	o.Action.Unset()
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *AuditEntry) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditEntry) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *AuditEntry) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *AuditEntry) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetJobId returns the JobId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuditEntry) GetJobId() string {
	if o == nil || IsNil(o.JobId.Get()) {
		var ret string
		return ret
	}
	return *o.JobId.Get()
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditEntry) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobId.Get(), o.JobId.IsSet()
}

// HasJobId returns a boolean if a field has been set.
func (o *AuditEntry) HasJobId() bool {
	if o != nil && o.JobId.IsSet() {
		return true
	}

	return false
}

// SetJobId gets a reference to the given NullableString and assigns it to the JobId field.
func (o *AuditEntry) SetJobId(v string) {
	o.JobId.Set(&v)
}
// SetJobIdNil sets the value for JobId to be an explicit nil
func (o *AuditEntry) SetJobIdNil() {
	o.JobId.Set(nil)
}

// UnsetJobId ensures that no value is present for JobId, not even an explicit nil
func (o *AuditEntry) UnsetJobId() {
	o.JobId.Unset()
}

// GetEvaluationId returns the EvaluationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuditEntry) GetEvaluationId() string {
	if o == nil || IsNil(o.EvaluationId.Get()) {
		var ret string
		return ret
	}
	return *o.EvaluationId.Get()
}

// GetEvaluationIdOk returns a tuple with the EvaluationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditEntry) GetEvaluationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EvaluationId.Get(), o.EvaluationId.IsSet()
}

// HasEvaluationId returns a boolean if a field has been set.
func (o *AuditEntry) HasEvaluationId() bool {
	if o != nil && o.EvaluationId.IsSet() {
		return true
	}

	return false
}

// SetEvaluationId gets a reference to the given NullableString and assigns it to the EvaluationId field.
func (o *AuditEntry) SetEvaluationId(v string) {
	o.EvaluationId.Set(&v)
}
// SetEvaluationIdNil sets the value for EvaluationId to be an explicit nil
func (o *AuditEntry) SetEvaluationIdNil() {
	o.EvaluationId.Set(nil)
}

// UnsetEvaluationId ensures that no value is present for EvaluationId, not even an explicit nil
func (o *AuditEntry) UnsetEvaluationId() {
	o.EvaluationId.Unset()
}

func (o AuditEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["event_type"] = o.EventType
	if o.PolicyId.IsSet() {
		toSerialize["policy_id"] = o.PolicyId.Get()
	}
	if o.RuleId.IsSet() {
		toSerialize["rule_id"] = o.RuleId.Get()
	}
	if o.RecordId.IsSet() {
		toSerialize["record_id"] = o.RecordId.Get()
	}
	if o.Action.IsSet() {
		toSerialize["action"] = o.Action.Get()
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if o.JobId.IsSet() {
		toSerialize["job_id"] = o.JobId.Get()
	}
	if o.EvaluationId.IsSet() {
		toSerialize["evaluation_id"] = o.EvaluationId.Get()
	}
	return toSerialize, nil
}

func (o *AuditEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_at",
		"event_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditEntry := _AuditEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditEntry)

	if err != nil {
		return err
	}

	*o = AuditEntry(varAuditEntry)

	return err
}

type NullableAuditEntry struct {
	value *AuditEntry
	isSet bool
}

func (v NullableAuditEntry) Get() *AuditEntry {
	return v.value
}

func (v *NullableAuditEntry) Set(val *AuditEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditEntry(val *AuditEntry) *NullableAuditEntry {
	return &NullableAuditEntry{value: val, isSet: true}
}

func (v NullableAuditEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


