/*
DRPE — Data Retention Policy Engine

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DetectedEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetectedEntity{}

// DetectedEntity A single entity hit from classification.
type DetectedEntity struct {
	EntityId string `json:"entity_id"`
	Label string `json:"label"`
	Field string `json:"field"`
	Classification DataClassification `json:"classification"`
	Sensitivity Sensitivity `json:"sensitivity"`
	Confidence *string `json:"confidence,omitempty"`
	Snippet NullableString `json:"snippet,omitempty"`
	Detector string `json:"detector"`
	RegulatoryRefs []string `json:"regulatory_refs,omitempty"`
}

type _DetectedEntity DetectedEntity

// NewDetectedEntity instantiates a new DetectedEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectedEntity(entityId string, label string, field string, classification DataClassification, sensitivity Sensitivity, detector string) *DetectedEntity {
	this := DetectedEntity{}
	this.EntityId = entityId
	this.Label = label
	this.Field = field
	this.Classification = classification
	this.Sensitivity = sensitivity
	var confidence string = "definitive"
	this.Confidence = &confidence
	this.Detector = detector
	return &this
}

// NewDetectedEntityWithDefaults instantiates a new DetectedEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectedEntityWithDefaults() *DetectedEntity {
	this := DetectedEntity{}
	var confidence string = "definitive"
	this.Confidence = &confidence
	return &this
}

// GetEntityId returns the EntityId field value
func (o *DetectedEntity) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *DetectedEntity) SetEntityId(v string) {
	o.EntityId = v
}

// GetLabel returns the Label field value
func (o *DetectedEntity) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *DetectedEntity) SetLabel(v string) {
	o.Label = v
}

// GetField returns the Field field value
func (o *DetectedEntity) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *DetectedEntity) SetField(v string) {
	o.Field = v
}

// GetClassification returns the Classification field value
func (o *DetectedEntity) GetClassification() DataClassification {
	if o == nil {
		var ret DataClassification
		return ret
	}

	return o.Classification
}

// GetClassificationOk returns a tuple with the Classification field value
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetClassificationOk() (*DataClassification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Classification, true
}

// SetClassification sets field value
func (o *DetectedEntity) SetClassification(v DataClassification) {
	o.Classification = v
}

// GetSensitivity returns the Sensitivity field value
func (o *DetectedEntity) GetSensitivity() Sensitivity {
	if o == nil {
		var ret Sensitivity
		return ret
	}

	return o.Sensitivity
}

// GetSensitivityOk returns a tuple with the Sensitivity field value
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetSensitivityOk() (*Sensitivity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sensitivity, true
}

// SetSensitivity sets field value
func (o *DetectedEntity) SetSensitivity(v Sensitivity) {
	o.Sensitivity = v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *DetectedEntity) GetConfidence() string {
	if o == nil || IsNil(o.Confidence) {
		var ret string
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetConfidenceOk() (*string, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *DetectedEntity) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given string and assigns it to the Confidence field.
func (o *DetectedEntity) SetConfidence(v string) {
	o.Confidence = &v
}

// GetSnippet returns the Snippet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DetectedEntity) GetSnippet() string {
	if o == nil || IsNil(o.Snippet.Get()) {
		var ret string
		return ret
	}
	return *o.Snippet.Get()
}

// GetSnippetOk returns a tuple with the Snippet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DetectedEntity) GetSnippetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Snippet.Get(), o.Snippet.IsSet()
}

// HasSnippet returns a boolean if a field has been set.
func (o *DetectedEntity) HasSnippet() bool {
	if o != nil && o.Snippet.IsSet() {
		return true
	}

	return false
}

// SetSnippet gets a reference to the given NullableString and assigns it to the Snippet field.
func (o *DetectedEntity) SetSnippet(v string) {
	o.Snippet.Set(&v)
}
// SetSnippetNil sets the value for Snippet to be an explicit nil
func (o *DetectedEntity) SetSnippetNil() {
	o.Snippet.Set(nil)
}

// UnsetSnippet ensures that no value is present for Snippet, not even an explicit nil
func (o *DetectedEntity) UnsetSnippet() {
	o.Snippet.Unset()
}

// GetDetector returns the Detector field value
func (o *DetectedEntity) GetDetector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detector
}

// GetDetectorOk returns a tuple with the Detector field value
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetDetectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detector, true
}

// SetDetector sets field value
func (o *DetectedEntity) SetDetector(v string) {
	o.Detector = v
}

// GetRegulatoryRefs returns the RegulatoryRefs field value if set, zero value otherwise.
func (o *DetectedEntity) GetRegulatoryRefs() []string {
	if o == nil || IsNil(o.RegulatoryRefs) {
		var ret []string
		return ret
	}
	return o.RegulatoryRefs
}

// GetRegulatoryRefsOk returns a tuple with the RegulatoryRefs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectedEntity) GetRegulatoryRefsOk() ([]string, bool) {
	if o == nil || IsNil(o.RegulatoryRefs) {
		return nil, false
	}
	return o.RegulatoryRefs, true
}

// HasRegulatoryRefs returns a boolean if a field has been set.
func (o *DetectedEntity) HasRegulatoryRefs() bool {
	if o != nil && !IsNil(o.RegulatoryRefs) {
		return true
	}

	return false
}

// SetRegulatoryRefs gets a reference to the given []string and assigns it to the RegulatoryRefs field.
func (o *DetectedEntity) SetRegulatoryRefs(v []string) {
	o.RegulatoryRefs = v
}

func (o DetectedEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetectedEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entity_id"] = o.EntityId
	toSerialize["label"] = o.Label
	toSerialize["field"] = o.Field
	toSerialize["classification"] = o.Classification
	toSerialize["sensitivity"] = o.Sensitivity
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if o.Snippet.IsSet() {
		toSerialize["snippet"] = o.Snippet.Get()
	}
	toSerialize["detector"] = o.Detector
	if !IsNil(o.RegulatoryRefs) {
		toSerialize["regulatory_refs"] = o.RegulatoryRefs
	}
	return toSerialize, nil
}

func (o *DetectedEntity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_id",
		"label",
		"field",
		"classification",
		"sensitivity",
		"detector",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetectedEntity := _DetectedEntity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetectedEntity)

	if err != nil {
		return err
	}

	*o = DetectedEntity(varDetectedEntity)

	return err
}

type NullableDetectedEntity struct {
	value *DetectedEntity
	isSet bool
}

func (v NullableDetectedEntity) Get() *DetectedEntity {
	return v.value
}

func (v *NullableDetectedEntity) Set(val *DetectedEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectedEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectedEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectedEntity(val *DetectedEntity) *NullableDetectedEntity {
	return &NullableDetectedEntity{value: val, isSet: true}
}

func (v NullableDetectedEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectedEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


