/*
DRPE — Data Retention Policy Engine

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchClassificationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchClassificationRequest{}

// BatchClassificationRequest struct for BatchClassificationRequest
type BatchClassificationRequest struct {
	Records []ClassificationRequest `json:"records"`
}

type _BatchClassificationRequest BatchClassificationRequest

// NewBatchClassificationRequest instantiates a new BatchClassificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchClassificationRequest(records []ClassificationRequest) *BatchClassificationRequest {
	this := BatchClassificationRequest{}
	this.Records = records
	return &this
}

// NewBatchClassificationRequestWithDefaults instantiates a new BatchClassificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchClassificationRequestWithDefaults() *BatchClassificationRequest {
	this := BatchClassificationRequest{}
	return &this
}

// GetRecords returns the Records field value
func (o *BatchClassificationRequest) GetRecords() []ClassificationRequest {
	if o == nil {
		var ret []ClassificationRequest
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *BatchClassificationRequest) GetRecordsOk() ([]ClassificationRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *BatchClassificationRequest) SetRecords(v []ClassificationRequest) {
	o.Records = v
}

func (o BatchClassificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchClassificationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records
	return toSerialize, nil
}

func (o *BatchClassificationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchClassificationRequest := _BatchClassificationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchClassificationRequest)

	if err != nil {
		return err
	}

	*o = BatchClassificationRequest(varBatchClassificationRequest)

	return err
}

type NullableBatchClassificationRequest struct {
	value *BatchClassificationRequest
	isSet bool
}

func (v NullableBatchClassificationRequest) Get() *BatchClassificationRequest {
	return v.value
}

func (v *NullableBatchClassificationRequest) Set(val *BatchClassificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchClassificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchClassificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchClassificationRequest(val *BatchClassificationRequest) *NullableBatchClassificationRequest {
	return &NullableBatchClassificationRequest{value: val, isSet: true}
}

func (v NullableBatchClassificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchClassificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


