/*
DRPE — Data Retention Policy Engine

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DsarSubmitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DsarSubmitRequest{}

// DsarSubmitRequest POST /api/v1/dsar/access|erasure body.
type DsarSubmitRequest struct {
	SubjectId string `json:"subject_id"`
	PolicyId string `json:"policy_id"`
	Identity map[string]interface{} `json:"identity,omitempty"`
	Records []RecordRef `json:"records,omitempty"`
}

type _DsarSubmitRequest DsarSubmitRequest

// NewDsarSubmitRequest instantiates a new DsarSubmitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDsarSubmitRequest(subjectId string, policyId string) *DsarSubmitRequest {
	this := DsarSubmitRequest{}
	this.SubjectId = subjectId
	this.PolicyId = policyId
	return &this
}

// NewDsarSubmitRequestWithDefaults instantiates a new DsarSubmitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDsarSubmitRequestWithDefaults() *DsarSubmitRequest {
	this := DsarSubmitRequest{}
	return &this
}

// GetSubjectId returns the SubjectId field value
func (o *DsarSubmitRequest) GetSubjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value
// and a boolean to check if the value has been set.
func (o *DsarSubmitRequest) GetSubjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectId, true
}

// SetSubjectId sets field value
func (o *DsarSubmitRequest) SetSubjectId(v string) {
	o.SubjectId = v
}

// GetPolicyId returns the PolicyId field value
func (o *DsarSubmitRequest) GetPolicyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value
// and a boolean to check if the value has been set.
func (o *DsarSubmitRequest) GetPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyId, true
}

// SetPolicyId sets field value
func (o *DsarSubmitRequest) SetPolicyId(v string) {
	o.PolicyId = v
}

// GetIdentity returns the Identity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DsarSubmitRequest) GetIdentity() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DsarSubmitRequest) GetIdentityOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Identity) {
		return map[string]interface{}{}, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *DsarSubmitRequest) HasIdentity() bool {
	if o != nil && !IsNil(o.Identity) {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given map[string]interface{} and assigns it to the Identity field.
func (o *DsarSubmitRequest) SetIdentity(v map[string]interface{}) {
	o.Identity = v
}

// GetRecords returns the Records field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DsarSubmitRequest) GetRecords() []RecordRef {
	if o == nil {
		var ret []RecordRef
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DsarSubmitRequest) GetRecordsOk() ([]RecordRef, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *DsarSubmitRequest) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []RecordRef and assigns it to the Records field.
func (o *DsarSubmitRequest) SetRecords(v []RecordRef) {
	o.Records = v
}

func (o DsarSubmitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DsarSubmitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject_id"] = o.SubjectId
	toSerialize["policy_id"] = o.PolicyId
	if o.Identity != nil {
		toSerialize["identity"] = o.Identity
	}
	if o.Records != nil {
		toSerialize["records"] = o.Records
	}
	return toSerialize, nil
}

func (o *DsarSubmitRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject_id",
		"policy_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDsarSubmitRequest := _DsarSubmitRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDsarSubmitRequest)

	if err != nil {
		return err
	}

	*o = DsarSubmitRequest(varDsarSubmitRequest)

	return err
}

type NullableDsarSubmitRequest struct {
	value *DsarSubmitRequest
	isSet bool
}

func (v NullableDsarSubmitRequest) Get() *DsarSubmitRequest {
	return v.value
}

func (v *NullableDsarSubmitRequest) Set(val *DsarSubmitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDsarSubmitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDsarSubmitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDsarSubmitRequest(val *DsarSubmitRequest) *NullableDsarSubmitRequest {
	return &NullableDsarSubmitRequest{value: val, isSet: true}
}

func (v NullableDsarSubmitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDsarSubmitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


