/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateResponse{}

// ValidateResponse struct for ValidateResponse
type ValidateResponse struct {
	Valid bool `json:"valid"`
	Policy NullablePolicy `json:"policy,omitempty"`
	ClassificationPolicy NullableClassificationPolicy `json:"classification_policy,omitempty"`
	PolicyKind NullablePolicyKind `json:"policy_kind,omitempty"`
	Errors []string `json:"errors,omitempty"`
}

type _ValidateResponse ValidateResponse

// NewValidateResponse instantiates a new ValidateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateResponse(valid bool) *ValidateResponse {
	this := ValidateResponse{}
	this.Valid = valid
	return &this
}

// NewValidateResponseWithDefaults instantiates a new ValidateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateResponseWithDefaults() *ValidateResponse {
	this := ValidateResponse{}
	return &this
}

// GetValid returns the Valid field value
func (o *ValidateResponse) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *ValidateResponse) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *ValidateResponse) SetValid(v bool) {
	o.Valid = v
}

// GetPolicy returns the Policy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ValidateResponse) GetPolicy() Policy {
	if o == nil || IsNil(o.Policy.Get()) {
		var ret Policy
		return ret
	}
	return *o.Policy.Get()
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ValidateResponse) GetPolicyOk() (*Policy, bool) {
	if o == nil {
		return nil, false
	}
	return o.Policy.Get(), o.Policy.IsSet()
}

// HasPolicy returns a boolean if a field has been set.
func (o *ValidateResponse) HasPolicy() bool {
	if o != nil && o.Policy.IsSet() {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given NullablePolicy and assigns it to the Policy field.
func (o *ValidateResponse) SetPolicy(v Policy) {
	o.Policy.Set(&v)
}
// SetPolicyNil sets the value for Policy to be an explicit nil
func (o *ValidateResponse) SetPolicyNil() {
	o.Policy.Set(nil)
}

// UnsetPolicy ensures that no value is present for Policy, not even an explicit nil
func (o *ValidateResponse) UnsetPolicy() {
	o.Policy.Unset()
}

// GetClassificationPolicy returns the ClassificationPolicy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ValidateResponse) GetClassificationPolicy() ClassificationPolicy {
	if o == nil || IsNil(o.ClassificationPolicy.Get()) {
		var ret ClassificationPolicy
		return ret
	}
	return *o.ClassificationPolicy.Get()
}

// GetClassificationPolicyOk returns a tuple with the ClassificationPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ValidateResponse) GetClassificationPolicyOk() (*ClassificationPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClassificationPolicy.Get(), o.ClassificationPolicy.IsSet()
}

// HasClassificationPolicy returns a boolean if a field has been set.
func (o *ValidateResponse) HasClassificationPolicy() bool {
	if o != nil && o.ClassificationPolicy.IsSet() {
		return true
	}

	return false
}

// SetClassificationPolicy gets a reference to the given NullableClassificationPolicy and assigns it to the ClassificationPolicy field.
func (o *ValidateResponse) SetClassificationPolicy(v ClassificationPolicy) {
	o.ClassificationPolicy.Set(&v)
}
// SetClassificationPolicyNil sets the value for ClassificationPolicy to be an explicit nil
func (o *ValidateResponse) SetClassificationPolicyNil() {
	o.ClassificationPolicy.Set(nil)
}

// UnsetClassificationPolicy ensures that no value is present for ClassificationPolicy, not even an explicit nil
func (o *ValidateResponse) UnsetClassificationPolicy() {
	o.ClassificationPolicy.Unset()
}

// GetPolicyKind returns the PolicyKind field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ValidateResponse) GetPolicyKind() PolicyKind {
	if o == nil || IsNil(o.PolicyKind.Get()) {
		var ret PolicyKind
		return ret
	}
	return *o.PolicyKind.Get()
}

// GetPolicyKindOk returns a tuple with the PolicyKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ValidateResponse) GetPolicyKindOk() (*PolicyKind, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyKind.Get(), o.PolicyKind.IsSet()
}

// HasPolicyKind returns a boolean if a field has been set.
func (o *ValidateResponse) HasPolicyKind() bool {
	if o != nil && o.PolicyKind.IsSet() {
		return true
	}

	return false
}

// SetPolicyKind gets a reference to the given NullablePolicyKind and assigns it to the PolicyKind field.
func (o *ValidateResponse) SetPolicyKind(v PolicyKind) {
	o.PolicyKind.Set(&v)
}
// SetPolicyKindNil sets the value for PolicyKind to be an explicit nil
func (o *ValidateResponse) SetPolicyKindNil() {
	o.PolicyKind.Set(nil)
}

// UnsetPolicyKind ensures that no value is present for PolicyKind, not even an explicit nil
func (o *ValidateResponse) UnsetPolicyKind() {
	o.PolicyKind.Unset()
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ValidateResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ValidateResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *ValidateResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o ValidateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["valid"] = o.Valid
	if o.Policy.IsSet() {
		toSerialize["policy"] = o.Policy.Get()
	}
	if o.ClassificationPolicy.IsSet() {
		toSerialize["classification_policy"] = o.ClassificationPolicy.Get()
	}
	if o.PolicyKind.IsSet() {
		toSerialize["policy_kind"] = o.PolicyKind.Get()
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *ValidateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"valid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateResponse := _ValidateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateResponse)

	if err != nil {
		return err
	}

	*o = ValidateResponse(varValidateResponse)

	return err
}

type NullableValidateResponse struct {
	value *ValidateResponse
	isSet bool
}

func (v NullableValidateResponse) Get() *ValidateResponse {
	return v.value
}

func (v *NullableValidateResponse) Set(val *ValidateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateResponse(val *ValidateResponse) *NullableValidateResponse {
	return &NullableValidateResponse{value: val, isSet: true}
}

func (v NullableValidateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


