/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogLinkSystemRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogLinkSystemRef{}

// CatalogLinkSystemRef Lean system ref for fleet graph / bulk catalog links.
type CatalogLinkSystemRef struct {
	Id string `json:"id"`
	Name string `json:"name"`
	SourceKey NullableString `json:"source_key,omitempty"`
}

type _CatalogLinkSystemRef CatalogLinkSystemRef

// NewCatalogLinkSystemRef instantiates a new CatalogLinkSystemRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogLinkSystemRef(id string, name string) *CatalogLinkSystemRef {
	this := CatalogLinkSystemRef{}
	this.Id = id
	this.Name = name
	return &this
}

// NewCatalogLinkSystemRefWithDefaults instantiates a new CatalogLinkSystemRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogLinkSystemRefWithDefaults() *CatalogLinkSystemRef {
	this := CatalogLinkSystemRef{}
	return &this
}

// GetId returns the Id field value
func (o *CatalogLinkSystemRef) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CatalogLinkSystemRef) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CatalogLinkSystemRef) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CatalogLinkSystemRef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CatalogLinkSystemRef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CatalogLinkSystemRef) SetName(v string) {
	o.Name = v
}

// GetSourceKey returns the SourceKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CatalogLinkSystemRef) GetSourceKey() string {
	if o == nil || IsNil(o.SourceKey.Get()) {
		var ret string
		return ret
	}
	return *o.SourceKey.Get()
}

// GetSourceKeyOk returns a tuple with the SourceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CatalogLinkSystemRef) GetSourceKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceKey.Get(), o.SourceKey.IsSet()
}

// HasSourceKey returns a boolean if a field has been set.
func (o *CatalogLinkSystemRef) HasSourceKey() bool {
	if o != nil && o.SourceKey.IsSet() {
		return true
	}

	return false
}

// SetSourceKey gets a reference to the given NullableString and assigns it to the SourceKey field.
func (o *CatalogLinkSystemRef) SetSourceKey(v string) {
	o.SourceKey.Set(&v)
}
// SetSourceKeyNil sets the value for SourceKey to be an explicit nil
func (o *CatalogLinkSystemRef) SetSourceKeyNil() {
	o.SourceKey.Set(nil)
}

// UnsetSourceKey ensures that no value is present for SourceKey, not even an explicit nil
func (o *CatalogLinkSystemRef) UnsetSourceKey() {
	o.SourceKey.Unset()
}

func (o CatalogLinkSystemRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogLinkSystemRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if o.SourceKey.IsSet() {
		toSerialize["source_key"] = o.SourceKey.Get()
	}
	return toSerialize, nil
}

func (o *CatalogLinkSystemRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogLinkSystemRef := _CatalogLinkSystemRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogLinkSystemRef)

	if err != nil {
		return err
	}

	*o = CatalogLinkSystemRef(varCatalogLinkSystemRef)

	return err
}

type NullableCatalogLinkSystemRef struct {
	value *CatalogLinkSystemRef
	isSet bool
}

func (v NullableCatalogLinkSystemRef) Get() *CatalogLinkSystemRef {
	return v.value
}

func (v *NullableCatalogLinkSystemRef) Set(val *CatalogLinkSystemRef) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogLinkSystemRef) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogLinkSystemRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogLinkSystemRef(val *CatalogLinkSystemRef) *NullableCatalogLinkSystemRef {
	return &NullableCatalogLinkSystemRef{value: val, isSet: true}
}

func (v NullableCatalogLinkSystemRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogLinkSystemRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


