/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
)

// checks if the GraceHoldActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraceHoldActionRequest{}

// GraceHoldActionRequest Optional body for force / cancel.
type GraceHoldActionRequest struct {
	Requester NullableString `json:"requester,omitempty"`
}

// NewGraceHoldActionRequest instantiates a new GraceHoldActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraceHoldActionRequest() *GraceHoldActionRequest {
	this := GraceHoldActionRequest{}
	return &this
}

// NewGraceHoldActionRequestWithDefaults instantiates a new GraceHoldActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraceHoldActionRequestWithDefaults() *GraceHoldActionRequest {
	this := GraceHoldActionRequest{}
	return &this
}

// GetRequester returns the Requester field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GraceHoldActionRequest) GetRequester() string {
	if o == nil || IsNil(o.Requester.Get()) {
		var ret string
		return ret
	}
	return *o.Requester.Get()
}

// GetRequesterOk returns a tuple with the Requester field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GraceHoldActionRequest) GetRequesterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Requester.Get(), o.Requester.IsSet()
}

// HasRequester returns a boolean if a field has been set.
func (o *GraceHoldActionRequest) HasRequester() bool {
	if o != nil && o.Requester.IsSet() {
		return true
	}

	return false
}

// SetRequester gets a reference to the given NullableString and assigns it to the Requester field.
func (o *GraceHoldActionRequest) SetRequester(v string) {
	o.Requester.Set(&v)
}
// SetRequesterNil sets the value for Requester to be an explicit nil
func (o *GraceHoldActionRequest) SetRequesterNil() {
	o.Requester.Set(nil)
}

// UnsetRequester ensures that no value is present for Requester, not even an explicit nil
func (o *GraceHoldActionRequest) UnsetRequester() {
	o.Requester.Unset()
}

func (o GraceHoldActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraceHoldActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Requester.IsSet() {
		toSerialize["requester"] = o.Requester.Get()
	}
	return toSerialize, nil
}

type NullableGraceHoldActionRequest struct {
	value *GraceHoldActionRequest
	isSet bool
}

func (v NullableGraceHoldActionRequest) Get() *GraceHoldActionRequest {
	return v.value
}

func (v *NullableGraceHoldActionRequest) Set(val *GraceHoldActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGraceHoldActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGraceHoldActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraceHoldActionRequest(val *GraceHoldActionRequest) *NullableGraceHoldActionRequest {
	return &NullableGraceHoldActionRequest{value: val, isSet: true}
}

func (v NullableGraceHoldActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraceHoldActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


