/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
)

// checks if the PolicyCatalogLinksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyCatalogLinksResponse{}

// PolicyCatalogLinksResponse Systems and processes linked to one policy (bulk catalog-links entry).
type PolicyCatalogLinksResponse struct {
	Systems []CatalogLinkSystemRef `json:"systems,omitempty"`
	Processes []CatalogLinkProcessRef `json:"processes,omitempty"`
}

// NewPolicyCatalogLinksResponse instantiates a new PolicyCatalogLinksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyCatalogLinksResponse() *PolicyCatalogLinksResponse {
	this := PolicyCatalogLinksResponse{}
	return &this
}

// NewPolicyCatalogLinksResponseWithDefaults instantiates a new PolicyCatalogLinksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyCatalogLinksResponseWithDefaults() *PolicyCatalogLinksResponse {
	this := PolicyCatalogLinksResponse{}
	return &this
}

// GetSystems returns the Systems field value if set, zero value otherwise.
func (o *PolicyCatalogLinksResponse) GetSystems() []CatalogLinkSystemRef {
	if o == nil || IsNil(o.Systems) {
		var ret []CatalogLinkSystemRef
		return ret
	}
	return o.Systems
}

// GetSystemsOk returns a tuple with the Systems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyCatalogLinksResponse) GetSystemsOk() ([]CatalogLinkSystemRef, bool) {
	if o == nil || IsNil(o.Systems) {
		return nil, false
	}
	return o.Systems, true
}

// HasSystems returns a boolean if a field has been set.
func (o *PolicyCatalogLinksResponse) HasSystems() bool {
	if o != nil && !IsNil(o.Systems) {
		return true
	}

	return false
}

// SetSystems gets a reference to the given []CatalogLinkSystemRef and assigns it to the Systems field.
func (o *PolicyCatalogLinksResponse) SetSystems(v []CatalogLinkSystemRef) {
	o.Systems = v
}

// GetProcesses returns the Processes field value if set, zero value otherwise.
func (o *PolicyCatalogLinksResponse) GetProcesses() []CatalogLinkProcessRef {
	if o == nil || IsNil(o.Processes) {
		var ret []CatalogLinkProcessRef
		return ret
	}
	return o.Processes
}

// GetProcessesOk returns a tuple with the Processes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyCatalogLinksResponse) GetProcessesOk() ([]CatalogLinkProcessRef, bool) {
	if o == nil || IsNil(o.Processes) {
		return nil, false
	}
	return o.Processes, true
}

// HasProcesses returns a boolean if a field has been set.
func (o *PolicyCatalogLinksResponse) HasProcesses() bool {
	if o != nil && !IsNil(o.Processes) {
		return true
	}

	return false
}

// SetProcesses gets a reference to the given []CatalogLinkProcessRef and assigns it to the Processes field.
func (o *PolicyCatalogLinksResponse) SetProcesses(v []CatalogLinkProcessRef) {
	o.Processes = v
}

func (o PolicyCatalogLinksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyCatalogLinksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Systems) {
		toSerialize["systems"] = o.Systems
	}
	if !IsNil(o.Processes) {
		toSerialize["processes"] = o.Processes
	}
	return toSerialize, nil
}

type NullablePolicyCatalogLinksResponse struct {
	value *PolicyCatalogLinksResponse
	isSet bool
}

func (v NullablePolicyCatalogLinksResponse) Get() *PolicyCatalogLinksResponse {
	return v.value
}

func (v *NullablePolicyCatalogLinksResponse) Set(val *PolicyCatalogLinksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyCatalogLinksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyCatalogLinksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyCatalogLinksResponse(val *PolicyCatalogLinksResponse) *NullablePolicyCatalogLinksResponse {
	return &NullablePolicyCatalogLinksResponse{value: val, isSet: true}
}

func (v NullablePolicyCatalogLinksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyCatalogLinksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


