/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProvenanceModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvenanceModel{}

// ProvenanceModel struct for ProvenanceModel
type ProvenanceModel struct {
	Source string `json:"source"`
	Trust string `json:"trust"`
	Ref NullableString `json:"ref,omitempty"`
	TaintTags []string `json:"taint_tags,omitempty"`
}

type _ProvenanceModel ProvenanceModel

// NewProvenanceModel instantiates a new ProvenanceModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvenanceModel(source string, trust string) *ProvenanceModel {
	this := ProvenanceModel{}
	this.Source = source
	this.Trust = trust
	return &this
}

// NewProvenanceModelWithDefaults instantiates a new ProvenanceModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvenanceModelWithDefaults() *ProvenanceModel {
	this := ProvenanceModel{}
	return &this
}

// GetSource returns the Source field value
func (o *ProvenanceModel) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ProvenanceModel) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ProvenanceModel) SetSource(v string) {
	o.Source = v
}

// GetTrust returns the Trust field value
func (o *ProvenanceModel) GetTrust() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Trust
}

// GetTrustOk returns a tuple with the Trust field value
// and a boolean to check if the value has been set.
func (o *ProvenanceModel) GetTrustOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trust, true
}

// SetTrust sets field value
func (o *ProvenanceModel) SetTrust(v string) {
	o.Trust = v
}

// GetRef returns the Ref field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvenanceModel) GetRef() string {
	if o == nil || IsNil(o.Ref.Get()) {
		var ret string
		return ret
	}
	return *o.Ref.Get()
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvenanceModel) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ref.Get(), o.Ref.IsSet()
}

// HasRef returns a boolean if a field has been set.
func (o *ProvenanceModel) HasRef() bool {
	if o != nil && o.Ref.IsSet() {
		return true
	}

	return false
}

// SetRef gets a reference to the given NullableString and assigns it to the Ref field.
func (o *ProvenanceModel) SetRef(v string) {
	o.Ref.Set(&v)
}
// SetRefNil sets the value for Ref to be an explicit nil
func (o *ProvenanceModel) SetRefNil() {
	o.Ref.Set(nil)
}

// UnsetRef ensures that no value is present for Ref, not even an explicit nil
func (o *ProvenanceModel) UnsetRef() {
	o.Ref.Unset()
}

// GetTaintTags returns the TaintTags field value if set, zero value otherwise.
func (o *ProvenanceModel) GetTaintTags() []string {
	if o == nil || IsNil(o.TaintTags) {
		var ret []string
		return ret
	}
	return o.TaintTags
}

// GetTaintTagsOk returns a tuple with the TaintTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvenanceModel) GetTaintTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.TaintTags) {
		return nil, false
	}
	return o.TaintTags, true
}

// HasTaintTags returns a boolean if a field has been set.
func (o *ProvenanceModel) HasTaintTags() bool {
	if o != nil && !IsNil(o.TaintTags) {
		return true
	}

	return false
}

// SetTaintTags gets a reference to the given []string and assigns it to the TaintTags field.
func (o *ProvenanceModel) SetTaintTags(v []string) {
	o.TaintTags = v
}

func (o ProvenanceModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvenanceModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["trust"] = o.Trust
	if o.Ref.IsSet() {
		toSerialize["ref"] = o.Ref.Get()
	}
	if !IsNil(o.TaintTags) {
		toSerialize["taint_tags"] = o.TaintTags
	}
	return toSerialize, nil
}

func (o *ProvenanceModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"trust",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProvenanceModel := _ProvenanceModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProvenanceModel)

	if err != nil {
		return err
	}

	*o = ProvenanceModel(varProvenanceModel)

	return err
}

type NullableProvenanceModel struct {
	value *ProvenanceModel
	isSet bool
}

func (v NullableProvenanceModel) Get() *ProvenanceModel {
	return v.value
}

func (v *NullableProvenanceModel) Set(val *ProvenanceModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProvenanceModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProvenanceModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvenanceModel(val *ProvenanceModel) *NullableProvenanceModel {
	return &NullableProvenanceModel{value: val, isSet: true}
}

func (v NullableProvenanceModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvenanceModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


