/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
)

// checks if the SystemUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemUpdateRequest{}

// SystemUpdateRequest PATCH /api/v1/systems/{id} body.
type SystemUpdateRequest struct {
	Name NullableString `json:"name,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Owner NullableString `json:"owner,omitempty"`
	Status NullableCatalogStatus `json:"status,omitempty"`
	SourceKey NullableString `json:"source_key,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

// NewSystemUpdateRequest instantiates a new SystemUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemUpdateRequest() *SystemUpdateRequest {
	this := SystemUpdateRequest{}
	return &this
}

// NewSystemUpdateRequestWithDefaults instantiates a new SystemUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemUpdateRequestWithDefaults() *SystemUpdateRequest {
	this := SystemUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *SystemUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *SystemUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *SystemUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *SystemUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SystemUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SystemUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SystemUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SystemUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemUpdateRequest) GetOwner() string {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret string
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemUpdateRequest) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *SystemUpdateRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableString and assigns it to the Owner field.
func (o *SystemUpdateRequest) SetOwner(v string) {
	o.Owner.Set(&v)
}
// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *SystemUpdateRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *SystemUpdateRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemUpdateRequest) GetStatus() CatalogStatus {
	if o == nil || IsNil(o.Status.Get()) {
		var ret CatalogStatus
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemUpdateRequest) GetStatusOk() (*CatalogStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *SystemUpdateRequest) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableCatalogStatus and assigns it to the Status field.
func (o *SystemUpdateRequest) SetStatus(v CatalogStatus) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *SystemUpdateRequest) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *SystemUpdateRequest) UnsetStatus() {
	o.Status.Unset()
}

// GetSourceKey returns the SourceKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemUpdateRequest) GetSourceKey() string {
	if o == nil || IsNil(o.SourceKey.Get()) {
		var ret string
		return ret
	}
	return *o.SourceKey.Get()
}

// GetSourceKeyOk returns a tuple with the SourceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemUpdateRequest) GetSourceKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceKey.Get(), o.SourceKey.IsSet()
}

// HasSourceKey returns a boolean if a field has been set.
func (o *SystemUpdateRequest) HasSourceKey() bool {
	if o != nil && o.SourceKey.IsSet() {
		return true
	}

	return false
}

// SetSourceKey gets a reference to the given NullableString and assigns it to the SourceKey field.
func (o *SystemUpdateRequest) SetSourceKey(v string) {
	o.SourceKey.Set(&v)
}
// SetSourceKeyNil sets the value for SourceKey to be an explicit nil
func (o *SystemUpdateRequest) SetSourceKeyNil() {
	o.SourceKey.Set(nil)
}

// UnsetSourceKey ensures that no value is present for SourceKey, not even an explicit nil
func (o *SystemUpdateRequest) UnsetSourceKey() {
	o.SourceKey.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemUpdateRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemUpdateRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SystemUpdateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SystemUpdateRequest) SetTags(v []string) {
	o.Tags = v
}

func (o SystemUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.SourceKey.IsSet() {
		toSerialize["source_key"] = o.SourceKey.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableSystemUpdateRequest struct {
	value *SystemUpdateRequest
	isSet bool
}

func (v NullableSystemUpdateRequest) Get() *SystemUpdateRequest {
	return v.value
}

func (v *NullableSystemUpdateRequest) Set(val *SystemUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemUpdateRequest(val *SystemUpdateRequest) *NullableSystemUpdateRequest {
	return &NullableSystemUpdateRequest{value: val, isSet: true}
}

func (v NullableSystemUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


