/*
DRPE — Data Retention Policy Engine

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
)

// checks if the DsarConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DsarConfig{}

// DsarConfig struct for DsarConfig
type DsarConfig struct {
	RightToAccess *bool `json:"right_to_access,omitempty"`
	RightToErasure *bool `json:"right_to_erasure,omitempty"`
	ErasureExceptions []string `json:"erasure_exceptions,omitempty"`
	ResponseDeadline NullableString `json:"response_deadline,omitempty"`
}

// NewDsarConfig instantiates a new DsarConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDsarConfig() *DsarConfig {
	this := DsarConfig{}
	var rightToAccess bool = true
	this.RightToAccess = &rightToAccess
	var rightToErasure bool = true
	this.RightToErasure = &rightToErasure
	return &this
}

// NewDsarConfigWithDefaults instantiates a new DsarConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDsarConfigWithDefaults() *DsarConfig {
	this := DsarConfig{}
	var rightToAccess bool = true
	this.RightToAccess = &rightToAccess
	var rightToErasure bool = true
	this.RightToErasure = &rightToErasure
	return &this
}

// GetRightToAccess returns the RightToAccess field value if set, zero value otherwise.
func (o *DsarConfig) GetRightToAccess() bool {
	if o == nil || IsNil(o.RightToAccess) {
		var ret bool
		return ret
	}
	return *o.RightToAccess
}

// GetRightToAccessOk returns a tuple with the RightToAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DsarConfig) GetRightToAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.RightToAccess) {
		return nil, false
	}
	return o.RightToAccess, true
}

// HasRightToAccess returns a boolean if a field has been set.
func (o *DsarConfig) HasRightToAccess() bool {
	if o != nil && !IsNil(o.RightToAccess) {
		return true
	}

	return false
}

// SetRightToAccess gets a reference to the given bool and assigns it to the RightToAccess field.
func (o *DsarConfig) SetRightToAccess(v bool) {
	o.RightToAccess = &v
}

// GetRightToErasure returns the RightToErasure field value if set, zero value otherwise.
func (o *DsarConfig) GetRightToErasure() bool {
	if o == nil || IsNil(o.RightToErasure) {
		var ret bool
		return ret
	}
	return *o.RightToErasure
}

// GetRightToErasureOk returns a tuple with the RightToErasure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DsarConfig) GetRightToErasureOk() (*bool, bool) {
	if o == nil || IsNil(o.RightToErasure) {
		return nil, false
	}
	return o.RightToErasure, true
}

// HasRightToErasure returns a boolean if a field has been set.
func (o *DsarConfig) HasRightToErasure() bool {
	if o != nil && !IsNil(o.RightToErasure) {
		return true
	}

	return false
}

// SetRightToErasure gets a reference to the given bool and assigns it to the RightToErasure field.
func (o *DsarConfig) SetRightToErasure(v bool) {
	o.RightToErasure = &v
}

// GetErasureExceptions returns the ErasureExceptions field value if set, zero value otherwise.
func (o *DsarConfig) GetErasureExceptions() []string {
	if o == nil || IsNil(o.ErasureExceptions) {
		var ret []string
		return ret
	}
	return o.ErasureExceptions
}

// GetErasureExceptionsOk returns a tuple with the ErasureExceptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DsarConfig) GetErasureExceptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.ErasureExceptions) {
		return nil, false
	}
	return o.ErasureExceptions, true
}

// HasErasureExceptions returns a boolean if a field has been set.
func (o *DsarConfig) HasErasureExceptions() bool {
	if o != nil && !IsNil(o.ErasureExceptions) {
		return true
	}

	return false
}

// SetErasureExceptions gets a reference to the given []string and assigns it to the ErasureExceptions field.
func (o *DsarConfig) SetErasureExceptions(v []string) {
	o.ErasureExceptions = v
}

// GetResponseDeadline returns the ResponseDeadline field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DsarConfig) GetResponseDeadline() string {
	if o == nil || IsNil(o.ResponseDeadline.Get()) {
		var ret string
		return ret
	}
	return *o.ResponseDeadline.Get()
}

// GetResponseDeadlineOk returns a tuple with the ResponseDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DsarConfig) GetResponseDeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseDeadline.Get(), o.ResponseDeadline.IsSet()
}

// HasResponseDeadline returns a boolean if a field has been set.
func (o *DsarConfig) HasResponseDeadline() bool {
	if o != nil && o.ResponseDeadline.IsSet() {
		return true
	}

	return false
}

// SetResponseDeadline gets a reference to the given NullableString and assigns it to the ResponseDeadline field.
func (o *DsarConfig) SetResponseDeadline(v string) {
	o.ResponseDeadline.Set(&v)
}
// SetResponseDeadlineNil sets the value for ResponseDeadline to be an explicit nil
func (o *DsarConfig) SetResponseDeadlineNil() {
	o.ResponseDeadline.Set(nil)
}

// UnsetResponseDeadline ensures that no value is present for ResponseDeadline, not even an explicit nil
func (o *DsarConfig) UnsetResponseDeadline() {
	o.ResponseDeadline.Unset()
}

func (o DsarConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DsarConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RightToAccess) {
		toSerialize["right_to_access"] = o.RightToAccess
	}
	if !IsNil(o.RightToErasure) {
		toSerialize["right_to_erasure"] = o.RightToErasure
	}
	if !IsNil(o.ErasureExceptions) {
		toSerialize["erasure_exceptions"] = o.ErasureExceptions
	}
	if o.ResponseDeadline.IsSet() {
		toSerialize["response_deadline"] = o.ResponseDeadline.Get()
	}
	return toSerialize, nil
}

type NullableDsarConfig struct {
	value *DsarConfig
	isSet bool
}

func (v NullableDsarConfig) Get() *DsarConfig {
	return v.value
}

func (v *NullableDsarConfig) Set(val *DsarConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDsarConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDsarConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDsarConfig(val *DsarConfig) *NullableDsarConfig {
	return &NullableDsarConfig{value: val, isSet: true}
}

func (v NullableDsarConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDsarConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


