/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClassificationPolicyScopeSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassificationPolicyScopeSummary{}

// ClassificationPolicyScopeSummary Subset of selected policy scope echoed for UI diagnostics.
type ClassificationPolicyScopeSummary struct {
	Jurisdiction string `json:"jurisdiction"`
	DataTypes []string `json:"data_types,omitempty"`
	Sources []string `json:"sources,omitempty"`
	ExcludedDataTypes []string `json:"excluded_data_types,omitempty"`
	ExcludedSources []string `json:"excluded_sources,omitempty"`
}

type _ClassificationPolicyScopeSummary ClassificationPolicyScopeSummary

// NewClassificationPolicyScopeSummary instantiates a new ClassificationPolicyScopeSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassificationPolicyScopeSummary(jurisdiction string) *ClassificationPolicyScopeSummary {
	this := ClassificationPolicyScopeSummary{}
	this.Jurisdiction = jurisdiction
	return &this
}

// NewClassificationPolicyScopeSummaryWithDefaults instantiates a new ClassificationPolicyScopeSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassificationPolicyScopeSummaryWithDefaults() *ClassificationPolicyScopeSummary {
	this := ClassificationPolicyScopeSummary{}
	return &this
}

// GetJurisdiction returns the Jurisdiction field value
func (o *ClassificationPolicyScopeSummary) GetJurisdiction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jurisdiction
}

// GetJurisdictionOk returns a tuple with the Jurisdiction field value
// and a boolean to check if the value has been set.
func (o *ClassificationPolicyScopeSummary) GetJurisdictionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jurisdiction, true
}

// SetJurisdiction sets field value
func (o *ClassificationPolicyScopeSummary) SetJurisdiction(v string) {
	o.Jurisdiction = v
}

// GetDataTypes returns the DataTypes field value if set, zero value otherwise.
func (o *ClassificationPolicyScopeSummary) GetDataTypes() []string {
	if o == nil || IsNil(o.DataTypes) {
		var ret []string
		return ret
	}
	return o.DataTypes
}

// GetDataTypesOk returns a tuple with the DataTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClassificationPolicyScopeSummary) GetDataTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.DataTypes) {
		return nil, false
	}
	return o.DataTypes, true
}

// HasDataTypes returns a boolean if a field has been set.
func (o *ClassificationPolicyScopeSummary) HasDataTypes() bool {
	if o != nil && !IsNil(o.DataTypes) {
		return true
	}

	return false
}

// SetDataTypes gets a reference to the given []string and assigns it to the DataTypes field.
func (o *ClassificationPolicyScopeSummary) SetDataTypes(v []string) {
	o.DataTypes = v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *ClassificationPolicyScopeSummary) GetSources() []string {
	if o == nil || IsNil(o.Sources) {
		var ret []string
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClassificationPolicyScopeSummary) GetSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *ClassificationPolicyScopeSummary) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []string and assigns it to the Sources field.
func (o *ClassificationPolicyScopeSummary) SetSources(v []string) {
	o.Sources = v
}

// GetExcludedDataTypes returns the ExcludedDataTypes field value if set, zero value otherwise.
func (o *ClassificationPolicyScopeSummary) GetExcludedDataTypes() []string {
	if o == nil || IsNil(o.ExcludedDataTypes) {
		var ret []string
		return ret
	}
	return o.ExcludedDataTypes
}

// GetExcludedDataTypesOk returns a tuple with the ExcludedDataTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClassificationPolicyScopeSummary) GetExcludedDataTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludedDataTypes) {
		return nil, false
	}
	return o.ExcludedDataTypes, true
}

// HasExcludedDataTypes returns a boolean if a field has been set.
func (o *ClassificationPolicyScopeSummary) HasExcludedDataTypes() bool {
	if o != nil && !IsNil(o.ExcludedDataTypes) {
		return true
	}

	return false
}

// SetExcludedDataTypes gets a reference to the given []string and assigns it to the ExcludedDataTypes field.
func (o *ClassificationPolicyScopeSummary) SetExcludedDataTypes(v []string) {
	o.ExcludedDataTypes = v
}

// GetExcludedSources returns the ExcludedSources field value if set, zero value otherwise.
func (o *ClassificationPolicyScopeSummary) GetExcludedSources() []string {
	if o == nil || IsNil(o.ExcludedSources) {
		var ret []string
		return ret
	}
	return o.ExcludedSources
}

// GetExcludedSourcesOk returns a tuple with the ExcludedSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClassificationPolicyScopeSummary) GetExcludedSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludedSources) {
		return nil, false
	}
	return o.ExcludedSources, true
}

// HasExcludedSources returns a boolean if a field has been set.
func (o *ClassificationPolicyScopeSummary) HasExcludedSources() bool {
	if o != nil && !IsNil(o.ExcludedSources) {
		return true
	}

	return false
}

// SetExcludedSources gets a reference to the given []string and assigns it to the ExcludedSources field.
func (o *ClassificationPolicyScopeSummary) SetExcludedSources(v []string) {
	o.ExcludedSources = v
}

func (o ClassificationPolicyScopeSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassificationPolicyScopeSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jurisdiction"] = o.Jurisdiction
	if !IsNil(o.DataTypes) {
		toSerialize["data_types"] = o.DataTypes
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.ExcludedDataTypes) {
		toSerialize["excluded_data_types"] = o.ExcludedDataTypes
	}
	if !IsNil(o.ExcludedSources) {
		toSerialize["excluded_sources"] = o.ExcludedSources
	}
	return toSerialize, nil
}

func (o *ClassificationPolicyScopeSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jurisdiction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassificationPolicyScopeSummary := _ClassificationPolicyScopeSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassificationPolicyScopeSummary)

	if err != nil {
		return err
	}

	*o = ClassificationPolicyScopeSummary(varClassificationPolicyScopeSummary)

	return err
}

type NullableClassificationPolicyScopeSummary struct {
	value *ClassificationPolicyScopeSummary
	isSet bool
}

func (v NullableClassificationPolicyScopeSummary) Get() *ClassificationPolicyScopeSummary {
	return v.value
}

func (v *NullableClassificationPolicyScopeSummary) Set(val *ClassificationPolicyScopeSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableClassificationPolicyScopeSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableClassificationPolicyScopeSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassificationPolicyScopeSummary(val *ClassificationPolicyScopeSummary) *NullableClassificationPolicyScopeSummary {
	return &NullableClassificationPolicyScopeSummary{value: val, isSet: true}
}

func (v NullableClassificationPolicyScopeSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassificationPolicyScopeSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


