/*
DRPE — Data Retention Policy Engine

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"fmt"
)


// EffectiveFrom struct for EffectiveFrom
type EffectiveFrom struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *EffectiveFrom) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(EffectiveFrom)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EffectiveFrom) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableEffectiveFrom struct {
	value *EffectiveFrom
	isSet bool
}

func (v NullableEffectiveFrom) Get() *EffectiveFrom {
	return v.value
}

func (v *NullableEffectiveFrom) Set(val *EffectiveFrom) {
	v.value = val
	v.isSet = true
}

func (v NullableEffectiveFrom) IsSet() bool {
	return v.isSet
}

func (v *NullableEffectiveFrom) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEffectiveFrom(val *EffectiveFrom) *NullableEffectiveFrom {
	return &NullableEffectiveFrom{value: val, isSet: true}
}

func (v NullableEffectiveFrom) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEffectiveFrom) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


