/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerdictResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerdictResponse{}

// VerdictResponse struct for VerdictResponse
type VerdictResponse struct {
	EventId string `json:"event_id"`
	GuardId string `json:"guard_id"`
	Provider string `json:"provider"`
	Decision string `json:"decision"`
	Categories []CategoryModel `json:"categories,omitempty"`
	Reasons []string `json:"reasons,omitempty"`
	Evidence []map[string]interface{} `json:"evidence,omitempty"`
	Confidence NullableFloat32 `json:"confidence,omitempty"`
	LatencyMs NullableFloat32 `json:"latency_ms,omitempty"`
	OgrVersion *string `json:"ogr_version,omitempty"`
}

type _VerdictResponse VerdictResponse

// NewVerdictResponse instantiates a new VerdictResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerdictResponse(eventId string, guardId string, provider string, decision string) *VerdictResponse {
	this := VerdictResponse{}
	this.EventId = eventId
	this.GuardId = guardId
	this.Provider = provider
	this.Decision = decision
	var ogrVersion string = "0.1"
	this.OgrVersion = &ogrVersion
	return &this
}

// NewVerdictResponseWithDefaults instantiates a new VerdictResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerdictResponseWithDefaults() *VerdictResponse {
	this := VerdictResponse{}
	var ogrVersion string = "0.1"
	this.OgrVersion = &ogrVersion
	return &this
}

// GetEventId returns the EventId field value
func (o *VerdictResponse) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *VerdictResponse) SetEventId(v string) {
	o.EventId = v
}

// GetGuardId returns the GuardId field value
func (o *VerdictResponse) GetGuardId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GuardId
}

// GetGuardIdOk returns a tuple with the GuardId field value
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetGuardIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GuardId, true
}

// SetGuardId sets field value
func (o *VerdictResponse) SetGuardId(v string) {
	o.GuardId = v
}

// GetProvider returns the Provider field value
func (o *VerdictResponse) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *VerdictResponse) SetProvider(v string) {
	o.Provider = v
}

// GetDecision returns the Decision field value
func (o *VerdictResponse) GetDecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *VerdictResponse) SetDecision(v string) {
	o.Decision = v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *VerdictResponse) GetCategories() []CategoryModel {
	if o == nil || IsNil(o.Categories) {
		var ret []CategoryModel
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetCategoriesOk() ([]CategoryModel, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *VerdictResponse) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []CategoryModel and assigns it to the Categories field.
func (o *VerdictResponse) SetCategories(v []CategoryModel) {
	o.Categories = v
}

// GetReasons returns the Reasons field value if set, zero value otherwise.
func (o *VerdictResponse) GetReasons() []string {
	if o == nil || IsNil(o.Reasons) {
		var ret []string
		return ret
	}
	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetReasonsOk() ([]string, bool) {
	if o == nil || IsNil(o.Reasons) {
		return nil, false
	}
	return o.Reasons, true
}

// HasReasons returns a boolean if a field has been set.
func (o *VerdictResponse) HasReasons() bool {
	if o != nil && !IsNil(o.Reasons) {
		return true
	}

	return false
}

// SetReasons gets a reference to the given []string and assigns it to the Reasons field.
func (o *VerdictResponse) SetReasons(v []string) {
	o.Reasons = v
}

// GetEvidence returns the Evidence field value if set, zero value otherwise.
func (o *VerdictResponse) GetEvidence() []map[string]interface{} {
	if o == nil || IsNil(o.Evidence) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Evidence
}

// GetEvidenceOk returns a tuple with the Evidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetEvidenceOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Evidence) {
		return nil, false
	}
	return o.Evidence, true
}

// HasEvidence returns a boolean if a field has been set.
func (o *VerdictResponse) HasEvidence() bool {
	if o != nil && !IsNil(o.Evidence) {
		return true
	}

	return false
}

// SetEvidence gets a reference to the given []map[string]interface{} and assigns it to the Evidence field.
func (o *VerdictResponse) SetEvidence(v []map[string]interface{}) {
	o.Evidence = v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerdictResponse) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence.Get()) {
		var ret float32
		return ret
	}
	return *o.Confidence.Get()
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerdictResponse) GetConfidenceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Confidence.Get(), o.Confidence.IsSet()
}

// HasConfidence returns a boolean if a field has been set.
func (o *VerdictResponse) HasConfidence() bool {
	if o != nil && o.Confidence.IsSet() {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given NullableFloat32 and assigns it to the Confidence field.
func (o *VerdictResponse) SetConfidence(v float32) {
	o.Confidence.Set(&v)
}
// SetConfidenceNil sets the value for Confidence to be an explicit nil
func (o *VerdictResponse) SetConfidenceNil() {
	o.Confidence.Set(nil)
}

// UnsetConfidence ensures that no value is present for Confidence, not even an explicit nil
func (o *VerdictResponse) UnsetConfidence() {
	o.Confidence.Unset()
}

// GetLatencyMs returns the LatencyMs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerdictResponse) GetLatencyMs() float32 {
	if o == nil || IsNil(o.LatencyMs.Get()) {
		var ret float32
		return ret
	}
	return *o.LatencyMs.Get()
}

// GetLatencyMsOk returns a tuple with the LatencyMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerdictResponse) GetLatencyMsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LatencyMs.Get(), o.LatencyMs.IsSet()
}

// HasLatencyMs returns a boolean if a field has been set.
func (o *VerdictResponse) HasLatencyMs() bool {
	if o != nil && o.LatencyMs.IsSet() {
		return true
	}

	return false
}

// SetLatencyMs gets a reference to the given NullableFloat32 and assigns it to the LatencyMs field.
func (o *VerdictResponse) SetLatencyMs(v float32) {
	o.LatencyMs.Set(&v)
}
// SetLatencyMsNil sets the value for LatencyMs to be an explicit nil
func (o *VerdictResponse) SetLatencyMsNil() {
	o.LatencyMs.Set(nil)
}

// UnsetLatencyMs ensures that no value is present for LatencyMs, not even an explicit nil
func (o *VerdictResponse) UnsetLatencyMs() {
	o.LatencyMs.Unset()
}

// GetOgrVersion returns the OgrVersion field value if set, zero value otherwise.
func (o *VerdictResponse) GetOgrVersion() string {
	if o == nil || IsNil(o.OgrVersion) {
		var ret string
		return ret
	}
	return *o.OgrVersion
}

// GetOgrVersionOk returns a tuple with the OgrVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerdictResponse) GetOgrVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OgrVersion) {
		return nil, false
	}
	return o.OgrVersion, true
}

// HasOgrVersion returns a boolean if a field has been set.
func (o *VerdictResponse) HasOgrVersion() bool {
	if o != nil && !IsNil(o.OgrVersion) {
		return true
	}

	return false
}

// SetOgrVersion gets a reference to the given string and assigns it to the OgrVersion field.
func (o *VerdictResponse) SetOgrVersion(v string) {
	o.OgrVersion = &v
}

func (o VerdictResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerdictResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["guard_id"] = o.GuardId
	toSerialize["provider"] = o.Provider
	toSerialize["decision"] = o.Decision
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Reasons) {
		toSerialize["reasons"] = o.Reasons
	}
	if !IsNil(o.Evidence) {
		toSerialize["evidence"] = o.Evidence
	}
	if o.Confidence.IsSet() {
		toSerialize["confidence"] = o.Confidence.Get()
	}
	if o.LatencyMs.IsSet() {
		toSerialize["latency_ms"] = o.LatencyMs.Get()
	}
	if !IsNil(o.OgrVersion) {
		toSerialize["ogr_version"] = o.OgrVersion
	}
	return toSerialize, nil
}

func (o *VerdictResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"guard_id",
		"provider",
		"decision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerdictResponse := _VerdictResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerdictResponse)

	if err != nil {
		return err
	}

	*o = VerdictResponse(varVerdictResponse)

	return err
}

type NullableVerdictResponse struct {
	value *VerdictResponse
	isSet bool
}

func (v NullableVerdictResponse) Get() *VerdictResponse {
	return v.value
}

func (v *NullableVerdictResponse) Set(val *VerdictResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerdictResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerdictResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerdictResponse(val *VerdictResponse) *NullableVerdictResponse {
	return &NullableVerdictResponse{value: val, isSet: true}
}

func (v NullableVerdictResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerdictResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


