/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogLinkProcessRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogLinkProcessRef{}

// CatalogLinkProcessRef Lean process ref for fleet graph / bulk catalog links.
type CatalogLinkProcessRef struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type _CatalogLinkProcessRef CatalogLinkProcessRef

// NewCatalogLinkProcessRef instantiates a new CatalogLinkProcessRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogLinkProcessRef(id string, name string) *CatalogLinkProcessRef {
	this := CatalogLinkProcessRef{}
	this.Id = id
	this.Name = name
	return &this
}

// NewCatalogLinkProcessRefWithDefaults instantiates a new CatalogLinkProcessRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogLinkProcessRefWithDefaults() *CatalogLinkProcessRef {
	this := CatalogLinkProcessRef{}
	return &this
}

// GetId returns the Id field value
func (o *CatalogLinkProcessRef) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CatalogLinkProcessRef) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CatalogLinkProcessRef) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CatalogLinkProcessRef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CatalogLinkProcessRef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CatalogLinkProcessRef) SetName(v string) {
	o.Name = v
}

func (o CatalogLinkProcessRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogLinkProcessRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CatalogLinkProcessRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogLinkProcessRef := _CatalogLinkProcessRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogLinkProcessRef)

	if err != nil {
		return err
	}

	*o = CatalogLinkProcessRef(varCatalogLinkProcessRef)

	return err
}

type NullableCatalogLinkProcessRef struct {
	value *CatalogLinkProcessRef
	isSet bool
}

func (v NullableCatalogLinkProcessRef) Get() *CatalogLinkProcessRef {
	return v.value
}

func (v *NullableCatalogLinkProcessRef) Set(val *CatalogLinkProcessRef) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogLinkProcessRef) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogLinkProcessRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogLinkProcessRef(val *CatalogLinkProcessRef) *NullableCatalogLinkProcessRef {
	return &NullableCatalogLinkProcessRef{value: val, isSet: true}
}

func (v NullableCatalogLinkProcessRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogLinkProcessRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


