/*
ROS Policy

Define, evaluate, and enforce data retention policies

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drpe

import (
	"encoding/json"
)

// checks if the EnforceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnforceRequest{}

// EnforceRequest POST /api/v1/enforce body.
type EnforceRequest struct {
	PolicyId NullableString `json:"policy_id,omitempty"`
	Records []RecordRef `json:"records,omitempty"`
}

// NewEnforceRequest instantiates a new EnforceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnforceRequest() *EnforceRequest {
	this := EnforceRequest{}
	return &this
}

// NewEnforceRequestWithDefaults instantiates a new EnforceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnforceRequestWithDefaults() *EnforceRequest {
	this := EnforceRequest{}
	return &this
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnforceRequest) GetPolicyId() string {
	if o == nil || IsNil(o.PolicyId.Get()) {
		var ret string
		return ret
	}
	return *o.PolicyId.Get()
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnforceRequest) GetPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyId.Get(), o.PolicyId.IsSet()
}

// HasPolicyId returns a boolean if a field has been set.
func (o *EnforceRequest) HasPolicyId() bool {
	if o != nil && o.PolicyId.IsSet() {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given NullableString and assigns it to the PolicyId field.
func (o *EnforceRequest) SetPolicyId(v string) {
	o.PolicyId.Set(&v)
}
// SetPolicyIdNil sets the value for PolicyId to be an explicit nil
func (o *EnforceRequest) SetPolicyIdNil() {
	o.PolicyId.Set(nil)
}

// UnsetPolicyId ensures that no value is present for PolicyId, not even an explicit nil
func (o *EnforceRequest) UnsetPolicyId() {
	o.PolicyId.Unset()
}

// GetRecords returns the Records field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnforceRequest) GetRecords() []RecordRef {
	if o == nil {
		var ret []RecordRef
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnforceRequest) GetRecordsOk() ([]RecordRef, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *EnforceRequest) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []RecordRef and assigns it to the Records field.
func (o *EnforceRequest) SetRecords(v []RecordRef) {
	o.Records = v
}

func (o EnforceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnforceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PolicyId.IsSet() {
		toSerialize["policy_id"] = o.PolicyId.Get()
	}
	if o.Records != nil {
		toSerialize["records"] = o.Records
	}
	return toSerialize, nil
}

type NullableEnforceRequest struct {
	value *EnforceRequest
	isSet bool
}

func (v NullableEnforceRequest) Get() *EnforceRequest {
	return v.value
}

func (v *NullableEnforceRequest) Set(val *EnforceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnforceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnforceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnforceRequest(val *EnforceRequest) *NullableEnforceRequest {
	return &NullableEnforceRequest{value: val, isSet: true}
}

func (v NullableEnforceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnforceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


