/*
 * DRPE — Data Retention Policy Engine
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import java.util.Objects;
import com.drpe.client.model.ClassificationDiagnostics;
import com.drpe.client.model.ClassificationResultDetail;
import com.drpe.client.model.DetectedEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.drpe.client.JSON;

/**
 * ClassificationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-22T15:59:15.048403+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.14.0")
public class ClassificationResponse {
  public static final String SERIALIZED_NAME_RECORD_ID = "record_id";
  @SerializedName(SERIALIZED_NAME_RECORD_ID)
  @javax.annotation.Nonnull
  private String recordId;

  public static final String SERIALIZED_NAME_CLASSIFICATION_ID = "classification_id";
  @SerializedName(SERIALIZED_NAME_CLASSIFICATION_ID)
  @javax.annotation.Nonnull
  private String classificationId;

  public static final String SERIALIZED_NAME_DETECTED_ENTITIES = "detected_entities";
  @SerializedName(SERIALIZED_NAME_DETECTED_ENTITIES)
  @javax.annotation.Nullable
  private List<DetectedEntity> detectedEntities = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  @javax.annotation.Nonnull
  private ClassificationResultDetail result;

  public static final String SERIALIZED_NAME_DIAGNOSTICS = "diagnostics";
  @SerializedName(SERIALIZED_NAME_DIAGNOSTICS)
  @javax.annotation.Nullable
  private ClassificationDiagnostics diagnostics;

  public static final String SERIALIZED_NAME_JURISDICTION_APPLIED = "jurisdiction_applied";
  @SerializedName(SERIALIZED_NAME_JURISDICTION_APPLIED)
  @javax.annotation.Nullable
  private String jurisdictionApplied;

  public static final String SERIALIZED_NAME_CLASSIFIED_AT = "classified_at";
  @SerializedName(SERIALIZED_NAME_CLASSIFIED_AT)
  @javax.annotation.Nonnull
  private String classifiedAt;

  public static final String SERIALIZED_NAME_AUDIT_REF = "audit_ref";
  @SerializedName(SERIALIZED_NAME_AUDIT_REF)
  @javax.annotation.Nullable
  private String auditRef;

  public ClassificationResponse() {
  }

  public ClassificationResponse recordId(@javax.annotation.Nonnull String recordId) {
    this.recordId = recordId;
    return this;
  }

  /**
   * Get recordId
   * @return recordId
   */
  @javax.annotation.Nonnull
  public String getRecordId() {
    return recordId;
  }

  public void setRecordId(@javax.annotation.Nonnull String recordId) {
    this.recordId = recordId;
  }


  public ClassificationResponse classificationId(@javax.annotation.Nonnull String classificationId) {
    this.classificationId = classificationId;
    return this;
  }

  /**
   * Get classificationId
   * @return classificationId
   */
  @javax.annotation.Nonnull
  public String getClassificationId() {
    return classificationId;
  }

  public void setClassificationId(@javax.annotation.Nonnull String classificationId) {
    this.classificationId = classificationId;
  }


  public ClassificationResponse detectedEntities(@javax.annotation.Nullable List<DetectedEntity> detectedEntities) {
    this.detectedEntities = detectedEntities;
    return this;
  }

  public ClassificationResponse addDetectedEntitiesItem(DetectedEntity detectedEntitiesItem) {
    if (this.detectedEntities == null) {
      this.detectedEntities = new ArrayList<>();
    }
    this.detectedEntities.add(detectedEntitiesItem);
    return this;
  }

  /**
   * Get detectedEntities
   * @return detectedEntities
   */
  @javax.annotation.Nullable
  public List<DetectedEntity> getDetectedEntities() {
    return detectedEntities;
  }

  public void setDetectedEntities(@javax.annotation.Nullable List<DetectedEntity> detectedEntities) {
    this.detectedEntities = detectedEntities;
  }


  public ClassificationResponse result(@javax.annotation.Nonnull ClassificationResultDetail result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @javax.annotation.Nonnull
  public ClassificationResultDetail getResult() {
    return result;
  }

  public void setResult(@javax.annotation.Nonnull ClassificationResultDetail result) {
    this.result = result;
  }


  public ClassificationResponse diagnostics(@javax.annotation.Nullable ClassificationDiagnostics diagnostics) {
    this.diagnostics = diagnostics;
    return this;
  }

  /**
   * Get diagnostics
   * @return diagnostics
   */
  @javax.annotation.Nullable
  public ClassificationDiagnostics getDiagnostics() {
    return diagnostics;
  }

  public void setDiagnostics(@javax.annotation.Nullable ClassificationDiagnostics diagnostics) {
    this.diagnostics = diagnostics;
  }


  public ClassificationResponse jurisdictionApplied(@javax.annotation.Nullable String jurisdictionApplied) {
    this.jurisdictionApplied = jurisdictionApplied;
    return this;
  }

  /**
   * Get jurisdictionApplied
   * @return jurisdictionApplied
   */
  @javax.annotation.Nullable
  public String getJurisdictionApplied() {
    return jurisdictionApplied;
  }

  public void setJurisdictionApplied(@javax.annotation.Nullable String jurisdictionApplied) {
    this.jurisdictionApplied = jurisdictionApplied;
  }


  public ClassificationResponse classifiedAt(@javax.annotation.Nonnull String classifiedAt) {
    this.classifiedAt = classifiedAt;
    return this;
  }

  /**
   * Get classifiedAt
   * @return classifiedAt
   */
  @javax.annotation.Nonnull
  public String getClassifiedAt() {
    return classifiedAt;
  }

  public void setClassifiedAt(@javax.annotation.Nonnull String classifiedAt) {
    this.classifiedAt = classifiedAt;
  }


  public ClassificationResponse auditRef(@javax.annotation.Nullable String auditRef) {
    this.auditRef = auditRef;
    return this;
  }

  /**
   * Get auditRef
   * @return auditRef
   */
  @javax.annotation.Nullable
  public String getAuditRef() {
    return auditRef;
  }

  public void setAuditRef(@javax.annotation.Nullable String auditRef) {
    this.auditRef = auditRef;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationResponse classificationResponse = (ClassificationResponse) o;
    return Objects.equals(this.recordId, classificationResponse.recordId) &&
        Objects.equals(this.classificationId, classificationResponse.classificationId) &&
        Objects.equals(this.detectedEntities, classificationResponse.detectedEntities) &&
        Objects.equals(this.result, classificationResponse.result) &&
        Objects.equals(this.diagnostics, classificationResponse.diagnostics) &&
        Objects.equals(this.jurisdictionApplied, classificationResponse.jurisdictionApplied) &&
        Objects.equals(this.classifiedAt, classificationResponse.classifiedAt) &&
        Objects.equals(this.auditRef, classificationResponse.auditRef);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(recordId, classificationId, detectedEntities, result, diagnostics, jurisdictionApplied, classifiedAt, auditRef);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationResponse {\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("    classificationId: ").append(toIndentedString(classificationId)).append("\n");
    sb.append("    detectedEntities: ").append(toIndentedString(detectedEntities)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    diagnostics: ").append(toIndentedString(diagnostics)).append("\n");
    sb.append("    jurisdictionApplied: ").append(toIndentedString(jurisdictionApplied)).append("\n");
    sb.append("    classifiedAt: ").append(toIndentedString(classifiedAt)).append("\n");
    sb.append("    auditRef: ").append(toIndentedString(auditRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("record_id", "classification_id", "detected_entities", "result", "diagnostics", "jurisdiction_applied", "classified_at", "audit_ref"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("record_id", "classification_id", "result", "classified_at"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ClassificationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClassificationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClassificationResponse is not found in the empty JSON string", ClassificationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClassificationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ClassificationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ClassificationResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("record_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `record_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("record_id").toString()));
      }
      if (!jsonObj.get("classification_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `classification_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("classification_id").toString()));
      }
      if (jsonObj.get("detected_entities") != null && !jsonObj.get("detected_entities").isJsonNull()) {
        JsonArray jsonArraydetectedEntities = jsonObj.getAsJsonArray("detected_entities");
        if (jsonArraydetectedEntities != null) {
          // ensure the json data is an array
          if (!jsonObj.get("detected_entities").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `detected_entities` to be an array in the JSON string but got `%s`", jsonObj.get("detected_entities").toString()));
          }

          // validate the optional field `detected_entities` (array)
          for (int i = 0; i < jsonArraydetectedEntities.size(); i++) {
            DetectedEntity.validateJsonElement(jsonArraydetectedEntities.get(i));
          };
        }
      }
      // validate the required field `result`
      ClassificationResultDetail.validateJsonElement(jsonObj.get("result"));
      // validate the optional field `diagnostics`
      if (jsonObj.get("diagnostics") != null && !jsonObj.get("diagnostics").isJsonNull()) {
        ClassificationDiagnostics.validateJsonElement(jsonObj.get("diagnostics"));
      }
      if ((jsonObj.get("jurisdiction_applied") != null && !jsonObj.get("jurisdiction_applied").isJsonNull()) && !jsonObj.get("jurisdiction_applied").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jurisdiction_applied` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jurisdiction_applied").toString()));
      }
      if (!jsonObj.get("classified_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `classified_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("classified_at").toString()));
      }
      if ((jsonObj.get("audit_ref") != null && !jsonObj.get("audit_ref").isJsonNull()) && !jsonObj.get("audit_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `audit_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audit_ref").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClassificationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClassificationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClassificationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClassificationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ClassificationResponse>() {
           @Override
           public void write(JsonWriter out, ClassificationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClassificationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ClassificationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ClassificationResponse
   * @throws IOException if the JSON string is invalid with respect to ClassificationResponse
   */
  public static ClassificationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClassificationResponse.class);
  }

  /**
   * Convert an instance of ClassificationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

