/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import java.util.Objects;
import com.drpe.client.model.DataClassification;
import com.drpe.client.model.EntityDetection;
import com.drpe.client.model.Sensitivity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.drpe.client.JSON;

/**
 * A detectable PII / sensitive data entity definition.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-24T12:43:19.315082+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.14.0")
public class ClassificationEntity {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nonnull
  private String label;

  public static final String SERIALIZED_NAME_CLASSIFICATION = "classification";
  @SerializedName(SERIALIZED_NAME_CLASSIFICATION)
  @javax.annotation.Nonnull
  private DataClassification classification;

  public static final String SERIALIZED_NAME_SENSITIVITY = "sensitivity";
  @SerializedName(SERIALIZED_NAME_SENSITIVITY)
  @javax.annotation.Nullable
  private Sensitivity sensitivity;

  public static final String SERIALIZED_NAME_REGULATORY_REFS = "regulatory_refs";
  @SerializedName(SERIALIZED_NAME_REGULATORY_REFS)
  @javax.annotation.Nullable
  private List<String> regulatoryRefs = new ArrayList<>();

  public static final String SERIALIZED_NAME_DETECTION = "detection";
  @SerializedName(SERIALIZED_NAME_DETECTION)
  @javax.annotation.Nullable
  private EntityDetection detection;

  public ClassificationEntity() {
  }

  public ClassificationEntity id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public ClassificationEntity label(@javax.annotation.Nonnull String label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nonnull
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nonnull String label) {
    this.label = label;
  }


  public ClassificationEntity classification(@javax.annotation.Nonnull DataClassification classification) {
    this.classification = classification;
    return this;
  }

  /**
   * Get classification
   * @return classification
   */
  @javax.annotation.Nonnull
  public DataClassification getClassification() {
    return classification;
  }

  public void setClassification(@javax.annotation.Nonnull DataClassification classification) {
    this.classification = classification;
  }


  public ClassificationEntity sensitivity(@javax.annotation.Nullable Sensitivity sensitivity) {
    this.sensitivity = sensitivity;
    return this;
  }

  /**
   * Get sensitivity
   * @return sensitivity
   */
  @javax.annotation.Nullable
  public Sensitivity getSensitivity() {
    return sensitivity;
  }

  public void setSensitivity(@javax.annotation.Nullable Sensitivity sensitivity) {
    this.sensitivity = sensitivity;
  }


  public ClassificationEntity regulatoryRefs(@javax.annotation.Nullable List<String> regulatoryRefs) {
    this.regulatoryRefs = regulatoryRefs;
    return this;
  }

  public ClassificationEntity addRegulatoryRefsItem(String regulatoryRefsItem) {
    if (this.regulatoryRefs == null) {
      this.regulatoryRefs = new ArrayList<>();
    }
    this.regulatoryRefs.add(regulatoryRefsItem);
    return this;
  }

  /**
   * Get regulatoryRefs
   * @return regulatoryRefs
   */
  @javax.annotation.Nullable
  public List<String> getRegulatoryRefs() {
    return regulatoryRefs;
  }

  public void setRegulatoryRefs(@javax.annotation.Nullable List<String> regulatoryRefs) {
    this.regulatoryRefs = regulatoryRefs;
  }


  public ClassificationEntity detection(@javax.annotation.Nullable EntityDetection detection) {
    this.detection = detection;
    return this;
  }

  /**
   * Get detection
   * @return detection
   */
  @javax.annotation.Nullable
  public EntityDetection getDetection() {
    return detection;
  }

  public void setDetection(@javax.annotation.Nullable EntityDetection detection) {
    this.detection = detection;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationEntity classificationEntity = (ClassificationEntity) o;
    return Objects.equals(this.id, classificationEntity.id) &&
        Objects.equals(this.label, classificationEntity.label) &&
        Objects.equals(this.classification, classificationEntity.classification) &&
        Objects.equals(this.sensitivity, classificationEntity.sensitivity) &&
        Objects.equals(this.regulatoryRefs, classificationEntity.regulatoryRefs) &&
        Objects.equals(this.detection, classificationEntity.detection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, classification, sensitivity, regulatoryRefs, detection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationEntity {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    sensitivity: ").append(toIndentedString(sensitivity)).append("\n");
    sb.append("    regulatoryRefs: ").append(toIndentedString(regulatoryRefs)).append("\n");
    sb.append("    detection: ").append(toIndentedString(detection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "label", "classification", "sensitivity", "regulatory_refs", "detection"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "label", "classification"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ClassificationEntity
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClassificationEntity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClassificationEntity is not found in the empty JSON string", ClassificationEntity.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClassificationEntity.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ClassificationEntity` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ClassificationEntity.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      // validate the required field `classification`
      DataClassification.validateJsonElement(jsonObj.get("classification"));
      // validate the optional field `sensitivity`
      if (jsonObj.get("sensitivity") != null && !jsonObj.get("sensitivity").isJsonNull()) {
        Sensitivity.validateJsonElement(jsonObj.get("sensitivity"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("regulatory_refs") != null && !jsonObj.get("regulatory_refs").isJsonNull() && !jsonObj.get("regulatory_refs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `regulatory_refs` to be an array in the JSON string but got `%s`", jsonObj.get("regulatory_refs").toString()));
      }
      // validate the optional field `detection`
      if (jsonObj.get("detection") != null && !jsonObj.get("detection").isJsonNull()) {
        EntityDetection.validateJsonElement(jsonObj.get("detection"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClassificationEntity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClassificationEntity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClassificationEntity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClassificationEntity.class));

       return (TypeAdapter<T>) new TypeAdapter<ClassificationEntity>() {
           @Override
           public void write(JsonWriter out, ClassificationEntity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClassificationEntity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ClassificationEntity given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ClassificationEntity
   * @throws IOException if the JSON string is invalid with respect to ClassificationEntity
   */
  public static ClassificationEntity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClassificationEntity.class);
  }

  /**
   * Convert an instance of ClassificationEntity to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

