/*
 * DRPE — Data Retention Policy Engine
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import java.util.Objects;
import com.drpe.client.model.FieldCondition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.drpe.client.JSON;

/**
 * Compound condition: all (AND) or any (OR) of field conditions.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-22T15:59:15.048403+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.14.0")
public class ConditionGroup {
  public static final String SERIALIZED_NAME_ALL = "all";
  @SerializedName(SERIALIZED_NAME_ALL)
  @javax.annotation.Nullable
  private List<FieldCondition> all;

  public static final String SERIALIZED_NAME_ANY = "any";
  @SerializedName(SERIALIZED_NAME_ANY)
  @javax.annotation.Nullable
  private List<FieldCondition> any;

  public ConditionGroup() {
  }

  public ConditionGroup all(@javax.annotation.Nullable List<FieldCondition> all) {
    this.all = all;
    return this;
  }

  public ConditionGroup addAllItem(FieldCondition allItem) {
    if (this.all == null) {
      this.all = new ArrayList<>();
    }
    this.all.add(allItem);
    return this;
  }

  /**
   * Get all
   * @return all
   */
  @javax.annotation.Nullable
  public List<FieldCondition> getAll() {
    return all;
  }

  public void setAll(@javax.annotation.Nullable List<FieldCondition> all) {
    this.all = all;
  }


  public ConditionGroup any(@javax.annotation.Nullable List<FieldCondition> any) {
    this.any = any;
    return this;
  }

  public ConditionGroup addAnyItem(FieldCondition anyItem) {
    if (this.any == null) {
      this.any = new ArrayList<>();
    }
    this.any.add(anyItem);
    return this;
  }

  /**
   * Get any
   * @return any
   */
  @javax.annotation.Nullable
  public List<FieldCondition> getAny() {
    return any;
  }

  public void setAny(@javax.annotation.Nullable List<FieldCondition> any) {
    this.any = any;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConditionGroup conditionGroup = (ConditionGroup) o;
    return Objects.equals(this.all, conditionGroup.all) &&
        Objects.equals(this.any, conditionGroup.any);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(all, any);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConditionGroup {\n");
    sb.append("    all: ").append(toIndentedString(all)).append("\n");
    sb.append("    any: ").append(toIndentedString(any)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("all", "any"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConditionGroup
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConditionGroup.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConditionGroup is not found in the empty JSON string", ConditionGroup.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConditionGroup.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConditionGroup` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("all") != null && !jsonObj.get("all").isJsonNull()) {
        JsonArray jsonArrayall = jsonObj.getAsJsonArray("all");
        if (jsonArrayall != null) {
          // ensure the json data is an array
          if (!jsonObj.get("all").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `all` to be an array in the JSON string but got `%s`", jsonObj.get("all").toString()));
          }

          // validate the optional field `all` (array)
          for (int i = 0; i < jsonArrayall.size(); i++) {
            FieldCondition.validateJsonElement(jsonArrayall.get(i));
          };
        }
      }
      if (jsonObj.get("any") != null && !jsonObj.get("any").isJsonNull()) {
        JsonArray jsonArrayany = jsonObj.getAsJsonArray("any");
        if (jsonArrayany != null) {
          // ensure the json data is an array
          if (!jsonObj.get("any").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `any` to be an array in the JSON string but got `%s`", jsonObj.get("any").toString()));
          }

          // validate the optional field `any` (array)
          for (int i = 0; i < jsonArrayany.size(); i++) {
            FieldCondition.validateJsonElement(jsonArrayany.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConditionGroup.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConditionGroup' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConditionGroup> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConditionGroup.class));

       return (TypeAdapter<T>) new TypeAdapter<ConditionGroup>() {
           @Override
           public void write(JsonWriter out, ConditionGroup value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConditionGroup read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConditionGroup given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConditionGroup
   * @throws IOException if the JSON string is invalid with respect to ConditionGroup
   */
  public static ConditionGroup fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConditionGroup.class);
  }

  /**
   * Convert an instance of ConditionGroup to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

