/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import java.util.Objects;
import com.drpe.client.model.DsarDeniedRecord;
import com.drpe.client.model.DsarError;
import com.drpe.client.model.RecordRef;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.drpe.client.JSON;

/**
 * Outcome payload stored on a DSAR request after processing.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-24T12:43:19.315082+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.14.0")
public class DsarResult {
  public static final String SERIALIZED_NAME_RECORDS = "records";
  @SerializedName(SERIALIZED_NAME_RECORDS)
  @javax.annotation.Nullable
  private List<RecordRef> records = new ArrayList<>();

  public static final String SERIALIZED_NAME_ERASED = "erased";
  @SerializedName(SERIALIZED_NAME_ERASED)
  @javax.annotation.Nullable
  private List<String> erased = new ArrayList<>();

  public static final String SERIALIZED_NAME_DENIED = "denied";
  @SerializedName(SERIALIZED_NAME_DENIED)
  @javax.annotation.Nullable
  private List<DsarDeniedRecord> denied = new ArrayList<>();

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  @javax.annotation.Nullable
  private List<DsarError> errors = new ArrayList<>();

  public DsarResult() {
  }

  public DsarResult records(@javax.annotation.Nullable List<RecordRef> records) {
    this.records = records;
    return this;
  }

  public DsarResult addRecordsItem(RecordRef recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * Get records
   * @return records
   */
  @javax.annotation.Nullable
  public List<RecordRef> getRecords() {
    return records;
  }

  public void setRecords(@javax.annotation.Nullable List<RecordRef> records) {
    this.records = records;
  }


  public DsarResult erased(@javax.annotation.Nullable List<String> erased) {
    this.erased = erased;
    return this;
  }

  public DsarResult addErasedItem(String erasedItem) {
    if (this.erased == null) {
      this.erased = new ArrayList<>();
    }
    this.erased.add(erasedItem);
    return this;
  }

  /**
   * Get erased
   * @return erased
   */
  @javax.annotation.Nullable
  public List<String> getErased() {
    return erased;
  }

  public void setErased(@javax.annotation.Nullable List<String> erased) {
    this.erased = erased;
  }


  public DsarResult denied(@javax.annotation.Nullable List<DsarDeniedRecord> denied) {
    this.denied = denied;
    return this;
  }

  public DsarResult addDeniedItem(DsarDeniedRecord deniedItem) {
    if (this.denied == null) {
      this.denied = new ArrayList<>();
    }
    this.denied.add(deniedItem);
    return this;
  }

  /**
   * Get denied
   * @return denied
   */
  @javax.annotation.Nullable
  public List<DsarDeniedRecord> getDenied() {
    return denied;
  }

  public void setDenied(@javax.annotation.Nullable List<DsarDeniedRecord> denied) {
    this.denied = denied;
  }


  public DsarResult errors(@javax.annotation.Nullable List<DsarError> errors) {
    this.errors = errors;
    return this;
  }

  public DsarResult addErrorsItem(DsarError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nullable
  public List<DsarError> getErrors() {
    return errors;
  }

  public void setErrors(@javax.annotation.Nullable List<DsarError> errors) {
    this.errors = errors;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DsarResult dsarResult = (DsarResult) o;
    return Objects.equals(this.records, dsarResult.records) &&
        Objects.equals(this.erased, dsarResult.erased) &&
        Objects.equals(this.denied, dsarResult.denied) &&
        Objects.equals(this.errors, dsarResult.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, erased, denied, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DsarResult {\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    erased: ").append(toIndentedString(erased)).append("\n");
    sb.append("    denied: ").append(toIndentedString(denied)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("records", "erased", "denied", "errors"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DsarResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DsarResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DsarResult is not found in the empty JSON string", DsarResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DsarResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DsarResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("records") != null && !jsonObj.get("records").isJsonNull()) {
        JsonArray jsonArrayrecords = jsonObj.getAsJsonArray("records");
        if (jsonArrayrecords != null) {
          // ensure the json data is an array
          if (!jsonObj.get("records").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `records` to be an array in the JSON string but got `%s`", jsonObj.get("records").toString()));
          }

          // validate the optional field `records` (array)
          for (int i = 0; i < jsonArrayrecords.size(); i++) {
            RecordRef.validateJsonElement(jsonArrayrecords.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("erased") != null && !jsonObj.get("erased").isJsonNull() && !jsonObj.get("erased").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `erased` to be an array in the JSON string but got `%s`", jsonObj.get("erased").toString()));
      }
      if (jsonObj.get("denied") != null && !jsonObj.get("denied").isJsonNull()) {
        JsonArray jsonArraydenied = jsonObj.getAsJsonArray("denied");
        if (jsonArraydenied != null) {
          // ensure the json data is an array
          if (!jsonObj.get("denied").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `denied` to be an array in the JSON string but got `%s`", jsonObj.get("denied").toString()));
          }

          // validate the optional field `denied` (array)
          for (int i = 0; i < jsonArraydenied.size(); i++) {
            DsarDeniedRecord.validateJsonElement(jsonArraydenied.get(i));
          };
        }
      }
      if (jsonObj.get("errors") != null && !jsonObj.get("errors").isJsonNull()) {
        JsonArray jsonArrayerrors = jsonObj.getAsJsonArray("errors");
        if (jsonArrayerrors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("errors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `errors` to be an array in the JSON string but got `%s`", jsonObj.get("errors").toString()));
          }

          // validate the optional field `errors` (array)
          for (int i = 0; i < jsonArrayerrors.size(); i++) {
            DsarError.validateJsonElement(jsonArrayerrors.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DsarResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DsarResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DsarResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DsarResult.class));

       return (TypeAdapter<T>) new TypeAdapter<DsarResult>() {
           @Override
           public void write(JsonWriter out, DsarResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DsarResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DsarResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DsarResult
   * @throws IOException if the JSON string is invalid with respect to DsarResult
   */
  public static DsarResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DsarResult.class);
  }

  /**
   * Convert an instance of DsarResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

