/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import java.util.Objects;
import com.drpe.client.model.AuditConfig;
import com.drpe.client.model.DataClassification;
import com.drpe.client.model.DsarConfig;
import com.drpe.client.model.EffectiveFrom;
import com.drpe.client.model.ExpiresAt;
import com.drpe.client.model.PolicyKind;
import com.drpe.client.model.PolicyRule;
import com.drpe.client.model.PolicyScope;
import com.drpe.client.model.PolicyStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.drpe.client.JSON;

/**
 * Full retention policy definition.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-22T15:59:15.048403+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.14.0")
public class Policy {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nullable
  private Integer version = 1;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private PolicyStatus status;

  public static final String SERIALIZED_NAME_JURISDICTION = "jurisdiction";
  @SerializedName(SERIALIZED_NAME_JURISDICTION)
  @javax.annotation.Nonnull
  private String jurisdiction;

  public static final String SERIALIZED_NAME_POLICY_KIND = "policy_kind";
  @SerializedName(SERIALIZED_NAME_POLICY_KIND)
  @javax.annotation.Nullable
  private PolicyKind policyKind;

  public static final String SERIALIZED_NAME_DATA_CLASSIFICATION = "data_classification";
  @SerializedName(SERIALIZED_NAME_DATA_CLASSIFICATION)
  @javax.annotation.Nonnull
  private DataClassification dataClassification;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private String owner;

  public static final String SERIALIZED_NAME_EFFECTIVE_FROM = "effective_from";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_FROM)
  @javax.annotation.Nullable
  private EffectiveFrom effectiveFrom;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private ExpiresAt expiresAt;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_SCOPE = "scope";
  @SerializedName(SERIALIZED_NAME_SCOPE)
  @javax.annotation.Nullable
  private PolicyScope scope;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  @javax.annotation.Nonnull
  private List<PolicyRule> rules = new ArrayList<>();

  public static final String SERIALIZED_NAME_DSAR = "dsar";
  @SerializedName(SERIALIZED_NAME_DSAR)
  @javax.annotation.Nullable
  private DsarConfig dsar;

  public static final String SERIALIZED_NAME_AUDIT = "audit";
  @SerializedName(SERIALIZED_NAME_AUDIT)
  @javax.annotation.Nullable
  private AuditConfig audit;

  public Policy() {
  }

  public Policy id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public Policy name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Policy version(@javax.annotation.Nullable Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Integer getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nullable Integer version) {
    this.version = version;
  }


  public Policy status(@javax.annotation.Nullable PolicyStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public PolicyStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable PolicyStatus status) {
    this.status = status;
  }


  public Policy jurisdiction(@javax.annotation.Nonnull String jurisdiction) {
    this.jurisdiction = jurisdiction;
    return this;
  }

  /**
   * Get jurisdiction
   * @return jurisdiction
   */
  @javax.annotation.Nonnull
  public String getJurisdiction() {
    return jurisdiction;
  }

  public void setJurisdiction(@javax.annotation.Nonnull String jurisdiction) {
    this.jurisdiction = jurisdiction;
  }


  public Policy policyKind(@javax.annotation.Nullable PolicyKind policyKind) {
    this.policyKind = policyKind;
    return this;
  }

  /**
   * Get policyKind
   * @return policyKind
   */
  @javax.annotation.Nullable
  public PolicyKind getPolicyKind() {
    return policyKind;
  }

  public void setPolicyKind(@javax.annotation.Nullable PolicyKind policyKind) {
    this.policyKind = policyKind;
  }


  public Policy dataClassification(@javax.annotation.Nonnull DataClassification dataClassification) {
    this.dataClassification = dataClassification;
    return this;
  }

  /**
   * Get dataClassification
   * @return dataClassification
   */
  @javax.annotation.Nonnull
  public DataClassification getDataClassification() {
    return dataClassification;
  }

  public void setDataClassification(@javax.annotation.Nonnull DataClassification dataClassification) {
    this.dataClassification = dataClassification;
  }


  public Policy owner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  public String getOwner() {
    return owner;
  }

  public void setOwner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
  }


  public Policy effectiveFrom(@javax.annotation.Nullable EffectiveFrom effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
    return this;
  }

  /**
   * Get effectiveFrom
   * @return effectiveFrom
   */
  @javax.annotation.Nullable
  public EffectiveFrom getEffectiveFrom() {
    return effectiveFrom;
  }

  public void setEffectiveFrom(@javax.annotation.Nullable EffectiveFrom effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
  }


  public Policy expiresAt(@javax.annotation.Nullable ExpiresAt expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public ExpiresAt getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable ExpiresAt expiresAt) {
    this.expiresAt = expiresAt;
  }


  public Policy tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Policy addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public Policy scope(@javax.annotation.Nullable PolicyScope scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @javax.annotation.Nullable
  public PolicyScope getScope() {
    return scope;
  }

  public void setScope(@javax.annotation.Nullable PolicyScope scope) {
    this.scope = scope;
  }


  public Policy rules(@javax.annotation.Nonnull List<PolicyRule> rules) {
    this.rules = rules;
    return this;
  }

  public Policy addRulesItem(PolicyRule rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Get rules
   * @return rules
   */
  @javax.annotation.Nonnull
  public List<PolicyRule> getRules() {
    return rules;
  }

  public void setRules(@javax.annotation.Nonnull List<PolicyRule> rules) {
    this.rules = rules;
  }


  public Policy dsar(@javax.annotation.Nullable DsarConfig dsar) {
    this.dsar = dsar;
    return this;
  }

  /**
   * Get dsar
   * @return dsar
   */
  @javax.annotation.Nullable
  public DsarConfig getDsar() {
    return dsar;
  }

  public void setDsar(@javax.annotation.Nullable DsarConfig dsar) {
    this.dsar = dsar;
  }


  public Policy audit(@javax.annotation.Nullable AuditConfig audit) {
    this.audit = audit;
    return this;
  }

  /**
   * Get audit
   * @return audit
   */
  @javax.annotation.Nullable
  public AuditConfig getAudit() {
    return audit;
  }

  public void setAudit(@javax.annotation.Nullable AuditConfig audit) {
    this.audit = audit;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Policy policy = (Policy) o;
    return Objects.equals(this.id, policy.id) &&
        Objects.equals(this.name, policy.name) &&
        Objects.equals(this.version, policy.version) &&
        Objects.equals(this.status, policy.status) &&
        Objects.equals(this.jurisdiction, policy.jurisdiction) &&
        Objects.equals(this.policyKind, policy.policyKind) &&
        Objects.equals(this.dataClassification, policy.dataClassification) &&
        Objects.equals(this.owner, policy.owner) &&
        Objects.equals(this.effectiveFrom, policy.effectiveFrom) &&
        Objects.equals(this.expiresAt, policy.expiresAt) &&
        Objects.equals(this.tags, policy.tags) &&
        Objects.equals(this.scope, policy.scope) &&
        Objects.equals(this.rules, policy.rules) &&
        Objects.equals(this.dsar, policy.dsar) &&
        Objects.equals(this.audit, policy.audit);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, version, status, jurisdiction, policyKind, dataClassification, owner, effectiveFrom, expiresAt, tags, scope, rules, dsar, audit);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Policy {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    jurisdiction: ").append(toIndentedString(jurisdiction)).append("\n");
    sb.append("    policyKind: ").append(toIndentedString(policyKind)).append("\n");
    sb.append("    dataClassification: ").append(toIndentedString(dataClassification)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    effectiveFrom: ").append(toIndentedString(effectiveFrom)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    dsar: ").append(toIndentedString(dsar)).append("\n");
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "version", "status", "jurisdiction", "policy_kind", "data_classification", "owner", "effective_from", "expires_at", "tags", "scope", "rules", "dsar", "audit"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "jurisdiction", "data_classification", "rules"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Policy
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Policy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Policy is not found in the empty JSON string", Policy.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Policy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Policy` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Policy.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        PolicyStatus.validateJsonElement(jsonObj.get("status"));
      }
      if (!jsonObj.get("jurisdiction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jurisdiction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jurisdiction").toString()));
      }
      // validate the optional field `policy_kind`
      if (jsonObj.get("policy_kind") != null && !jsonObj.get("policy_kind").isJsonNull()) {
        PolicyKind.validateJsonElement(jsonObj.get("policy_kind"));
      }
      // validate the required field `data_classification`
      DataClassification.validateJsonElement(jsonObj.get("data_classification"));
      if ((jsonObj.get("owner") != null && !jsonObj.get("owner").isJsonNull()) && !jsonObj.get("owner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `owner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner").toString()));
      }
      // validate the optional field `effective_from`
      if (jsonObj.get("effective_from") != null && !jsonObj.get("effective_from").isJsonNull()) {
        EffectiveFrom.validateJsonElement(jsonObj.get("effective_from"));
      }
      // validate the optional field `expires_at`
      if (jsonObj.get("expires_at") != null && !jsonObj.get("expires_at").isJsonNull()) {
        ExpiresAt.validateJsonElement(jsonObj.get("expires_at"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      // validate the optional field `scope`
      if (jsonObj.get("scope") != null && !jsonObj.get("scope").isJsonNull()) {
        PolicyScope.validateJsonElement(jsonObj.get("scope"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("rules").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `rules` to be an array in the JSON string but got `%s`", jsonObj.get("rules").toString()));
      }

      JsonArray jsonArrayrules = jsonObj.getAsJsonArray("rules");
      // validate the required field `rules` (array)
      for (int i = 0; i < jsonArrayrules.size(); i++) {
        PolicyRule.validateJsonElement(jsonArrayrules.get(i));
      };
      // validate the optional field `dsar`
      if (jsonObj.get("dsar") != null && !jsonObj.get("dsar").isJsonNull()) {
        DsarConfig.validateJsonElement(jsonObj.get("dsar"));
      }
      // validate the optional field `audit`
      if (jsonObj.get("audit") != null && !jsonObj.get("audit").isJsonNull()) {
        AuditConfig.validateJsonElement(jsonObj.get("audit"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Policy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Policy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Policy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Policy.class));

       return (TypeAdapter<T>) new TypeAdapter<Policy>() {
           @Override
           public void write(JsonWriter out, Policy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Policy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Policy given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Policy
   * @throws IOException if the JSON string is invalid with respect to Policy
   */
  public static Policy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Policy.class);
  }

  /**
   * Convert an instance of Policy to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

