/*
 * DRPE — Data Retention Policy Engine
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuditConfig
 */
public class AuditConfigTest {
    private final AuditConfig model = new AuditConfig();

    /**
     * Model tests for AuditConfig
     */
    @Test
    public void testAuditConfig() {
        // TODO: test AuditConfig
    }

    /**
     * Test the property 'logEvaluations'
     */
    @Test
    public void logEvaluationsTest() {
        // TODO: test logEvaluations
    }

    /**
     * Test the property 'logActions'
     */
    @Test
    public void logActionsTest() {
        // TODO: test logActions
    }

    /**
     * Test the property 'retentionOfAuditLogs'
     */
    @Test
    public void retentionOfAuditLogsTest() {
        // TODO: test retentionOfAuditLogs
    }

}
