/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import com.drpe.client.model.DataClassification;
import com.drpe.client.model.EntityDetection;
import com.drpe.client.model.Sensitivity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ClassificationEntity
 */
public class ClassificationEntityTest {
    private final ClassificationEntity model = new ClassificationEntity();

    /**
     * Model tests for ClassificationEntity
     */
    @Test
    public void testClassificationEntity() {
        // TODO: test ClassificationEntity
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'classification'
     */
    @Test
    public void classificationTest() {
        // TODO: test classification
    }

    /**
     * Test the property 'sensitivity'
     */
    @Test
    public void sensitivityTest() {
        // TODO: test sensitivity
    }

    /**
     * Test the property 'regulatoryRefs'
     */
    @Test
    public void regulatoryRefsTest() {
        // TODO: test regulatoryRefs
    }

    /**
     * Test the property 'detection'
     */
    @Test
    public void detectionTest() {
        // TODO: test detection
    }

}
