/*
 * DRPE — Data Retention Policy Engine
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import com.drpe.client.model.Action;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EvaluationResultDetail
 */
public class EvaluationResultDetailTest {
    private final EvaluationResultDetail model = new EvaluationResultDetail();

    /**
     * Model tests for EvaluationResultDetail
     */
    @Test
    public void testEvaluationResultDetail() {
        // TODO: test EvaluationResultDetail
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'matchedPolicy'
     */
    @Test
    public void matchedPolicyTest() {
        // TODO: test matchedPolicy
    }

    /**
     * Test the property 'matchedRule'
     */
    @Test
    public void matchedRuleTest() {
        // TODO: test matchedRule
    }

    /**
     * Test the property 'policyVersion'
     */
    @Test
    public void policyVersionTest() {
        // TODO: test policyVersion
    }

    /**
     * Test the property 'gracePeriodEnds'
     */
    @Test
    public void gracePeriodEndsTest() {
        // TODO: test gracePeriodEnds
    }

    /**
     * Test the property 'notifyAt'
     */
    @Test
    public void notifyAtTest() {
        // TODO: test notifyAt
    }

    /**
     * Test the property 'requiresApproval'
     */
    @Test
    public void requiresApprovalTest() {
        // TODO: test requiresApproval
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    public void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property 'archiveTarget'
     */
    @Test
    public void archiveTargetTest() {
        // TODO: test archiveTarget
    }

    /**
     * Test the property 'retainUntil'
     */
    @Test
    public void retainUntilTest() {
        // TODO: test retainUntil
    }

}
