/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import com.drpe.client.model.GraceHoldStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GraceHold
 */
public class GraceHoldTest {
    private final GraceHold model = new GraceHold();

    /**
     * Model tests for GraceHold
     */
    @Test
    public void testGraceHold() {
        // TODO: test GraceHold
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'policyId'
     */
    @Test
    public void policyIdTest() {
        // TODO: test policyId
    }

    /**
     * Test the property 'ruleId'
     */
    @Test
    public void ruleIdTest() {
        // TODO: test ruleId
    }

    /**
     * Test the property 'recordId'
     */
    @Test
    public void recordIdTest() {
        // TODO: test recordId
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'gracePeriodEnds'
     */
    @Test
    public void gracePeriodEndsTest() {
        // TODO: test gracePeriodEnds
    }

    /**
     * Test the property 'notifyAt'
     */
    @Test
    public void notifyAtTest() {
        // TODO: test notifyAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'closedAt'
     */
    @Test
    public void closedAtTest() {
        // TODO: test closedAt
    }

    /**
     * Test the property 'requester'
     */
    @Test
    public void requesterTest() {
        // TODO: test requester
    }

    /**
     * Test the property 'sourceJobId'
     */
    @Test
    public void sourceJobIdTest() {
        // TODO: test sourceJobId
    }

    /**
     * Test the property 'evaluationId'
     */
    @Test
    public void evaluationIdTest() {
        // TODO: test evaluationId
    }

}
