/*
 * DRPE — Data Retention Policy Engine
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PolicyDiffRequest
 */
public class PolicyDiffRequestTest {
    private final PolicyDiffRequest model = new PolicyDiffRequest();

    /**
     * Model tests for PolicyDiffRequest
     */
    @Test
    public void testPolicyDiffRequest() {
        // TODO: test PolicyDiffRequest
    }

    /**
     * Test the property 'fromVersion'
     */
    @Test
    public void fromVersionTest() {
        // TODO: test fromVersion
    }

    /**
     * Test the property 'toVersion'
     */
    @Test
    public void toVersionTest() {
        // TODO: test toVersion
    }

}
