/* tslint:disable */
/* eslint-disable */
/**
 * DRPE — Data Retention Policy Engine
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EnforceRequest,
  EnforceResponse,
  EnforcementJob,
  HTTPValidationError,
  JobStatus,
} from '../models/index';

export interface GetJobApiV1EnforceJobsJobIdGetRequest {
    jobId: string;
}

export interface ListJobsApiV1EnforceJobsGetRequest {
    status?: JobStatus | null;
    policyId?: string | null;
    limit?: number;
    offset?: number;
}

export interface TriggerEnforceApiV1EnforcePostRequest {
    enforceRequest: EnforceRequest;
}

/**
 * 
 */
export class EnforceApi extends runtime.BaseAPI {

    /**
     * Get Job
     */
    async getJobApiV1EnforceJobsJobIdGetRaw(requestParameters: GetJobApiV1EnforceJobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnforcementJob>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getJobApiV1EnforceJobsJobIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/enforce/jobs/{job_id}`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get Job
     */
    async getJobApiV1EnforceJobsJobIdGet(requestParameters: GetJobApiV1EnforceJobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnforcementJob> {
        const response = await this.getJobApiV1EnforceJobsJobIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Jobs
     */
    async listJobsApiV1EnforceJobsGetRaw(requestParameters: ListJobsApiV1EnforceJobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EnforcementJob>>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['policyId'] != null) {
            queryParameters['policy_id'] = requestParameters['policyId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/enforce/jobs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List Jobs
     */
    async listJobsApiV1EnforceJobsGet(requestParameters: ListJobsApiV1EnforceJobsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EnforcementJob>> {
        const response = await this.listJobsApiV1EnforceJobsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trigger Enforce
     */
    async triggerEnforceApiV1EnforcePostRaw(requestParameters: TriggerEnforceApiV1EnforcePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnforceResponse>> {
        if (requestParameters['enforceRequest'] == null) {
            throw new runtime.RequiredError(
                'enforceRequest',
                'Required parameter "enforceRequest" was null or undefined when calling triggerEnforceApiV1EnforcePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/enforce`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['enforceRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Trigger Enforce
     */
    async triggerEnforceApiV1EnforcePost(requestParameters: TriggerEnforceApiV1EnforcePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnforceResponse> {
        const response = await this.triggerEnforceApiV1EnforcePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
