/* tslint:disable */
/* eslint-disable */
/**
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EvaluateRequest,
  GuardrailPolicyCreateRequest,
  GuardrailPolicyResponse,
  GuardrailPolicyUpdateRequest,
  GuardrailsStatusResponse,
  HTTPValidationError,
  VerdictResponse,
} from '../models/index';

export interface CreateGuardrailPolicyApiV1GuardrailsPoliciesPostRequest {
    guardrailPolicyCreateRequest: GuardrailPolicyCreateRequest;
}

export interface DeleteGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdDeleteRequest {
    policyId: string;
}

export interface EvaluateGuardEventApiV1GuardrailsEvaluatePostRequest {
    evaluateRequest: EvaluateRequest;
}

export interface GetGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdGetRequest {
    policyId: string;
}

export interface ListGuardrailPoliciesApiV1GuardrailsPoliciesGetRequest {
    limit?: number;
    offset?: number;
}

export interface UpdateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPutRequest {
    policyId: string;
    guardrailPolicyUpdateRequest: GuardrailPolicyUpdateRequest;
}

/**
 * 
 */
export class GuardrailsApi extends runtime.BaseAPI {

    /**
     * Create Guardrail Policy
     */
    async createGuardrailPolicyApiV1GuardrailsPoliciesPostRaw(requestParameters: CreateGuardrailPolicyApiV1GuardrailsPoliciesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuardrailPolicyResponse>> {
        if (requestParameters['guardrailPolicyCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'guardrailPolicyCreateRequest',
                'Required parameter "guardrailPolicyCreateRequest" was null or undefined when calling createGuardrailPolicyApiV1GuardrailsPoliciesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/guardrails/policies`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['guardrailPolicyCreateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create Guardrail Policy
     */
    async createGuardrailPolicyApiV1GuardrailsPoliciesPost(requestParameters: CreateGuardrailPolicyApiV1GuardrailsPoliciesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuardrailPolicyResponse> {
        const response = await this.createGuardrailPolicyApiV1GuardrailsPoliciesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Guardrail Policy
     */
    async deleteGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdDeleteRaw(requestParameters: DeleteGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['policyId'] == null) {
            throw new runtime.RequiredError(
                'policyId',
                'Required parameter "policyId" was null or undefined when calling deleteGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/guardrails/policies/{policy_id}`;
        urlPath = urlPath.replace(`{${"policy_id"}}`, encodeURIComponent(String(requestParameters['policyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Guardrail Policy
     */
    async deleteGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdDelete(requestParameters: DeleteGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Evaluate Guard Event
     */
    async evaluateGuardEventApiV1GuardrailsEvaluatePostRaw(requestParameters: EvaluateGuardEventApiV1GuardrailsEvaluatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerdictResponse>> {
        if (requestParameters['evaluateRequest'] == null) {
            throw new runtime.RequiredError(
                'evaluateRequest',
                'Required parameter "evaluateRequest" was null or undefined when calling evaluateGuardEventApiV1GuardrailsEvaluatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/guardrails/evaluate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['evaluateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Evaluate Guard Event
     */
    async evaluateGuardEventApiV1GuardrailsEvaluatePost(requestParameters: EvaluateGuardEventApiV1GuardrailsEvaluatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerdictResponse> {
        const response = await this.evaluateGuardEventApiV1GuardrailsEvaluatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Guardrail Policy
     */
    async getGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdGetRaw(requestParameters: GetGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuardrailPolicyResponse>> {
        if (requestParameters['policyId'] == null) {
            throw new runtime.RequiredError(
                'policyId',
                'Required parameter "policyId" was null or undefined when calling getGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/guardrails/policies/{policy_id}`;
        urlPath = urlPath.replace(`{${"policy_id"}}`, encodeURIComponent(String(requestParameters['policyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get Guardrail Policy
     */
    async getGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdGet(requestParameters: GetGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuardrailPolicyResponse> {
        const response = await this.getGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Guardrails Status
     */
    async guardrailsStatusApiV1GuardrailsStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuardrailsStatusResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/guardrails/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Guardrails Status
     */
    async guardrailsStatusApiV1GuardrailsStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuardrailsStatusResponse> {
        const response = await this.guardrailsStatusApiV1GuardrailsStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Guardrail Policies
     */
    async listGuardrailPoliciesApiV1GuardrailsPoliciesGetRaw(requestParameters: ListGuardrailPoliciesApiV1GuardrailsPoliciesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GuardrailPolicyResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/guardrails/policies`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List Guardrail Policies
     */
    async listGuardrailPoliciesApiV1GuardrailsPoliciesGet(requestParameters: ListGuardrailPoliciesApiV1GuardrailsPoliciesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GuardrailPolicyResponse>> {
        const response = await this.listGuardrailPoliciesApiV1GuardrailsPoliciesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Guardrail Policy
     */
    async updateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPutRaw(requestParameters: UpdateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuardrailPolicyResponse>> {
        if (requestParameters['policyId'] == null) {
            throw new runtime.RequiredError(
                'policyId',
                'Required parameter "policyId" was null or undefined when calling updateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPut().'
            );
        }

        if (requestParameters['guardrailPolicyUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'guardrailPolicyUpdateRequest',
                'Required parameter "guardrailPolicyUpdateRequest" was null or undefined when calling updateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/guardrails/policies/{policy_id}`;
        urlPath = urlPath.replace(`{${"policy_id"}}`, encodeURIComponent(String(requestParameters['policyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['guardrailPolicyUpdateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update Guardrail Policy
     */
    async updateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPut(requestParameters: UpdateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuardrailPolicyResponse> {
        const response = await this.updateGuardrailPolicyApiV1GuardrailsPoliciesPolicyIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
