/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.api;

import com.drpe.client.ApiException;
import com.drpe.client.model.EnforceRequest;
import com.drpe.client.model.EnforceResponse;
import com.drpe.client.model.EnforcementJob;
import com.drpe.client.model.HTTPValidationError;
import com.drpe.client.model.JobStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnforceApi
 */
@Disabled
public class EnforceApiTest {

    private final EnforceApi api = new EnforceApi();

    /**
     * Get Job
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobApiV1EnforceJobsJobIdGetTest() throws ApiException {
        String jobId = null;
        EnforcementJob response = api.getJobApiV1EnforceJobsJobIdGet(jobId);
        // TODO: test validations
    }

    /**
     * List Jobs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listJobsApiV1EnforceJobsGetTest() throws ApiException {
        JobStatus status = null;
        String policyId = null;
        Integer limit = null;
        Integer offset = null;
        List<EnforcementJob> response = api.listJobsApiV1EnforceJobsGet(status, policyId, limit, offset);
        // TODO: test validations
    }

    /**
     * Trigger Enforce
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void triggerEnforceApiV1EnforcePostTest() throws ApiException {
        EnforceRequest enforceRequest = null;
        EnforceResponse response = api.triggerEnforceApiV1EnforcePost(enforceRequest);
        // TODO: test validations
    }

}
