/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.api;

import com.drpe.client.ApiException;
import com.drpe.client.model.HealthResponse;
import com.drpe.client.model.ReadyResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthApi
 */
@Disabled
public class HealthApiTest {

    private final HealthApi api = new HealthApi();

    /**
     * Health
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void healthApiV1HealthGetTest() throws ApiException {
        HealthResponse response = api.healthApiV1HealthGet();
        // TODO: test validations
    }

    /**
     * Ready
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readyApiV1HealthReadyGetTest() throws ApiException {
        ReadyResponse response = api.readyApiV1HealthReadyGet();
        // TODO: test validations
    }

}
