/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.api;

import com.drpe.client.ApiException;
import com.drpe.client.model.CatalogStatus;
import com.drpe.client.model.HTTPValidationError;
import com.drpe.client.model.PolicyIdsRequest;
import com.drpe.client.model.ProcessCreateRequest;
import com.drpe.client.model.ProcessResponse;
import com.drpe.client.model.ProcessUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProcessesApi
 */
@Disabled
public class ProcessesApiTest {

    private final ProcessesApi api = new ProcessesApi();

    /**
     * Create Process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProcessApiV1ProcessesPostTest() throws ApiException {
        ProcessCreateRequest processCreateRequest = null;
        ProcessResponse response = api.createProcessApiV1ProcessesPost(processCreateRequest);
        // TODO: test validations
    }

    /**
     * Delete Process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProcessApiV1ProcessesProcessIdDeleteTest() throws ApiException {
        String processId = null;
        api.deleteProcessApiV1ProcessesProcessIdDelete(processId);
        // TODO: test validations
    }

    /**
     * Get Process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProcessApiV1ProcessesProcessIdGetTest() throws ApiException {
        String processId = null;
        ProcessResponse response = api.getProcessApiV1ProcessesProcessIdGet(processId);
        // TODO: test validations
    }

    /**
     * List Process Policies
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProcessPoliciesApiV1ProcessesProcessIdPoliciesGetTest() throws ApiException {
        String processId = null;
        List<String> response = api.listProcessPoliciesApiV1ProcessesProcessIdPoliciesGet(processId);
        // TODO: test validations
    }

    /**
     * List Processes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProcessesApiV1ProcessesGetTest() throws ApiException {
        CatalogStatus status = null;
        Integer limit = null;
        Integer offset = null;
        List<ProcessResponse> response = api.listProcessesApiV1ProcessesGet(status, limit, offset);
        // TODO: test validations
    }

    /**
     * Set Process Policies
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setProcessPoliciesApiV1ProcessesProcessIdPoliciesPutTest() throws ApiException {
        String processId = null;
        PolicyIdsRequest policyIdsRequest = null;
        List<String> response = api.setProcessPoliciesApiV1ProcessesProcessIdPoliciesPut(processId, policyIdsRequest);
        // TODO: test validations
    }

    /**
     * Update Process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProcessApiV1ProcessesProcessIdPatchTest() throws ApiException {
        String processId = null;
        ProcessUpdateRequest processUpdateRequest = null;
        ProcessResponse response = api.updateProcessApiV1ProcessesProcessIdPatch(processId, processUpdateRequest);
        // TODO: test validations
    }

}
