/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.api;

import com.drpe.client.ApiException;
import com.drpe.client.model.CatalogStatus;
import com.drpe.client.model.HTTPValidationError;
import com.drpe.client.model.PolicyIdsRequest;
import com.drpe.client.model.SystemCreateRequest;
import com.drpe.client.model.SystemResponse;
import com.drpe.client.model.SystemUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemsApi
 */
@Disabled
public class SystemsApiTest {

    private final SystemsApi api = new SystemsApi();

    /**
     * Create System
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSystemApiV1SystemsPostTest() throws ApiException {
        SystemCreateRequest systemCreateRequest = null;
        SystemResponse response = api.createSystemApiV1SystemsPost(systemCreateRequest);
        // TODO: test validations
    }

    /**
     * Delete System
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSystemApiV1SystemsSystemIdDeleteTest() throws ApiException {
        String systemId = null;
        api.deleteSystemApiV1SystemsSystemIdDelete(systemId);
        // TODO: test validations
    }

    /**
     * Get System
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSystemApiV1SystemsSystemIdGetTest() throws ApiException {
        String systemId = null;
        SystemResponse response = api.getSystemApiV1SystemsSystemIdGet(systemId);
        // TODO: test validations
    }

    /**
     * List System Policies
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSystemPoliciesApiV1SystemsSystemIdPoliciesGetTest() throws ApiException {
        String systemId = null;
        List<String> response = api.listSystemPoliciesApiV1SystemsSystemIdPoliciesGet(systemId);
        // TODO: test validations
    }

    /**
     * List Systems
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSystemsApiV1SystemsGetTest() throws ApiException {
        CatalogStatus status = null;
        Integer limit = null;
        Integer offset = null;
        List<SystemResponse> response = api.listSystemsApiV1SystemsGet(status, limit, offset);
        // TODO: test validations
    }

    /**
     * Set System Policies
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setSystemPoliciesApiV1SystemsSystemIdPoliciesPutTest() throws ApiException {
        String systemId = null;
        PolicyIdsRequest policyIdsRequest = null;
        List<String> response = api.setSystemPoliciesApiV1SystemsSystemIdPoliciesPut(systemId, policyIdsRequest);
        // TODO: test validations
    }

    /**
     * Update System
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSystemApiV1SystemsSystemIdPatchTest() throws ApiException {
        String systemId = null;
        SystemUpdateRequest systemUpdateRequest = null;
        SystemResponse response = api.updateSystemApiV1SystemsSystemIdPatch(systemId, systemUpdateRequest);
        // TODO: test validations
    }

}
