/*
 * ROS Policy
 * Define, evaluate, and enforce data retention policies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.drpe.client.api;

import com.drpe.client.ApiException;
import com.drpe.client.model.HTTPValidationError;
import com.drpe.client.model.WebhookCreateRequest;
import com.drpe.client.model.WebhookCreateResponse;
import com.drpe.client.model.WebhookResponse;
import com.drpe.client.model.WebhookUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhooksApi
 */
@Disabled
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    /**
     * Create Webhook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWebhookApiV1WebhooksPostTest() throws ApiException {
        WebhookCreateRequest webhookCreateRequest = null;
        WebhookCreateResponse response = api.createWebhookApiV1WebhooksPost(webhookCreateRequest);
        // TODO: test validations
    }

    /**
     * Delete Webhook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteWebhookApiV1WebhooksWebhookIdDeleteTest() throws ApiException {
        String webhookId = null;
        api.deleteWebhookApiV1WebhooksWebhookIdDelete(webhookId);
        // TODO: test validations
    }

    /**
     * Get Webhook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWebhookApiV1WebhooksWebhookIdGetTest() throws ApiException {
        String webhookId = null;
        WebhookResponse response = api.getWebhookApiV1WebhooksWebhookIdGet(webhookId);
        // TODO: test validations
    }

    /**
     * List Webhooks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listWebhooksApiV1WebhooksGetTest() throws ApiException {
        Boolean active = null;
        Integer limit = null;
        Integer offset = null;
        List<WebhookResponse> response = api.listWebhooksApiV1WebhooksGet(active, limit, offset);
        // TODO: test validations
    }

    /**
     * Update Webhook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateWebhookApiV1WebhooksWebhookIdPatchTest() throws ApiException {
        String webhookId = null;
        WebhookUpdateRequest webhookUpdateRequest = null;
        WebhookResponse response = api.updateWebhookApiV1WebhooksWebhookIdPatch(webhookId, webhookUpdateRequest);
        // TODO: test validations
    }

}
